// Microsoft Azure certification tracks.
//
// Every exam code, duration, passing score, domain weighting, and skills-
// measured bullet below is read from Microsoft's own current certification
// pages and study guides at learn.microsoft.com -- not from memory. The
// certifications browse page is a JS-rendered filter UI and returns nothing
// to a plain fetch, so the roster of active (non-retired) certifications was
// pulled from Microsoft's public catalog API
// (learn.microsoft.com/api/catalog/?type=certifications&locale=en-us)
// instead. Objectives are written from the guide's skills-measured bullets,
// reworded into narrow single-concept objectives -- lesson format
// (guess/teach/fade/solo) needs one idea per objective -- paraphrased rather
// than copied, since the guides are Microsoft's own material.
//
// Building this strand certification by certification, same as AWS. Built so
// far: AZ-900 (Fundamentals), AZ-104 (Administrator Associate), AZ-305
// (Solutions Architect Expert), AI-901 (AI Fundamentals), DP-900 (Data
// Fundamentals), AZ-700 (Network Engineer Associate), AZ-140 (Virtual Desktop
// Specialty), DP-300 (Database Administrator Associate), AZ-400 (DevOps
// Engineer Expert), AZ-120 (Azure for SAP Workloads Specialty). Azure
// Developer Associate (AZ-204), Azure Security Engineer Associate (AZ-500),
// Azure Data Scientist Associate (DP-100), and Azure AI Engineer Associate
// (AI-102) are deliberately excluded -- all four retired with no active
// replacement exam as of this pass, part of the same 2026 "AI job boom"
// restructuring wave. Azure IoT Developer Specialty (AZ-220), Azure Stack Hub
// Operator Associate (AZ-600), and Azure Connectivity Support Engineer
// Specialty (AZ-720) are excluded too, retired 2023-07-31 in an earlier,
// unrelated cleanup. Azure Cosmos DB Developer Specialty (DP-420) is active
// today but renames to "Azure Cosmos DB AI Developer Associate" on
// 2026-10-06 with a new content guide -- deferred until after the rename
// rather than authoring soon-superseded material. No other niche specialty
// remains unconfirmed -- see the azure-catalog-progress memory file, which
// also tracks Microsoft's live 2026 retirement wave.
//
// Re-verify each track's `credential.lastVendorVerifiedAt` against the live
// certification page before release; migration 007 refuses to store any exam
// record outside 'draft' status without both an objectives URL and a
// verified date.

import type { SeedTrack } from "../data";

const AZURE_PROVIDER = {
  providerSlug: "microsoft",
  providerName: "Microsoft",
  providerUrl: "https://learn.microsoft.com/en-us/credentials/",
  subcategorySlug: "it-certifications",
  credentialType: "certification",
} as const;

const VERIFIED_AT = "2026-09-18T00:00:00Z";

// ---------------------------------------------------------------------------
// Foundational: Microsoft Certified: Azure Fundamentals (AZ-900)
// 45 minutes, scaled score 1-1000, minimum passing score 700.
// Domains: Cloud concepts 25-30% / Azure architecture and services 35-40% /
// Azure management and governance 30-35%.

export const AZURE_AZ900_TRACK: SeedTrack = {
  code: "AZ900",
  title: "Azure Fundamentals Coach",
  description:
    "Microsoft Certified: Azure Fundamentals (AZ-900): core cloud concepts, Azure's architecture and core services, and how cost, compliance, and governance work day to day in Azure.",
  trackType: "certification",
  subcategorySlug: "it-certifications",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/",
  sourceVerifiedAt: VERIFIED_AT,
  credential: {
    ...AZURE_PROVIDER,
    credentialSlug: "azure-fundamentals",
    credentialName: "Microsoft Certified: Azure Fundamentals",
    credentialUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/",
    examCode: "AZ-900",
    status: "active",
    officialObjectivesUrl: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-900",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "No prerequisites; Microsoft suggests familiarity with any area of IT (infrastructure, database, or software development) as helpful but not required.",
    durationMinutes: 45,
    questionFormat:
      "Multiple choice and multiple response; Microsoft does not publish an exact question count",
    passingScorePolicy: "Scaled score 1-1000; minimum passing score 700",
  },
  units: [
    {
      title: "Cloud Concepts",
      weight: 28,
      gate: "Given a cloud scenario, name the specific model, pricing approach, or service type at play and justify it against a stated cost, control, or availability requirement -- instead of reciting 'scalable and flexible'.",
      objectives: [
        "Defining cloud computing, and the shared responsibility model between customer and provider",
        "Public, private, and hybrid cloud models, and which situations fit each",
        "The consumption-based (pay-as-you-go) pricing model, and comparing it against other cloud pricing models",
        "What serverless computing means",
        "Benefits of high availability and scalability in the cloud",
        "Benefits of reliability and predictability in the cloud",
        "Benefits of security and governance in the cloud",
        "Benefits of manageability in the cloud",
        "Infrastructure as a service (IaaS), platform as a service (PaaS), and software as a service (SaaS)",
        "Choosing the right cloud service type -- IaaS, PaaS, or SaaS -- for a given use case",
      ],
    },
    {
      title: "Azure Architecture and Services",
      weight: 38,
      gate: "Given a workload's availability, data, or identity requirement, name the specific Azure building block that satisfies it -- not just 'use Azure'.",
      objectives: [
        "Azure regions, region pairs, and sovereign regions",
        "Availability zones",
        "Azure datacenters",
        "Azure resources and resource groups",
        "Azure subscriptions",
        "Azure management groups",
        "The hierarchy connecting resource groups, subscriptions, and management groups",
        "Comparing compute types: containers, virtual machines, and functions",
        "Virtual machine options: Azure Virtual Machines, Virtual Machine Scale Sets, availability sets, and Azure Virtual Desktop",
        "The resources a virtual machine requires",
        "Application hosting options: web apps, containers, and virtual machines",
        "Virtual networking concepts: virtual networks, subnets, peering, Azure DNS, Azure VPN Gateway, and Azure ExpressRoute",
        "Public versus private endpoints",
        "Comparing Azure Storage services",
        "Storage tiers",
        "Redundancy options for Azure Storage",
        "Storage account options and storage types",
        "Moving files into Azure: AzCopy, Azure Storage Explorer, and Azure File Sync",
        "Migration options: Azure Migrate and Azure Data Box",
        "Directory services in Azure: Microsoft Entra ID and Microsoft Entra Domain Services",
        "Authentication methods: single sign-on, multifactor authentication, and passwordless authentication",
        "External identities in Azure",
        "Microsoft Entra Conditional Access",
        "Azure role-based access control (RBAC)",
        "The concept of Zero Trust",
        "The defense-in-depth model",
        "The purpose of Microsoft Defender for Cloud",
      ],
    },
    {
      title: "Azure Management and Governance",
      weight: 33,
      gate: "Given a cost, compliance, or resource-management scenario, name the specific Azure tool that addresses it and what it would actually surface or enforce.",
      objectives: [
        "Factors that affect Azure costs",
        "The Azure pricing calculator",
        "Cost management capabilities in Azure",
        "The purpose of tags in Azure",
        "The purpose of Microsoft Purview in Azure",
        "The purpose of Azure Policy",
        "The purpose of resource locks",
        "The Azure portal",
        "Azure Cloud Shell, Azure CLI, and Azure PowerShell",
        "The purpose of Azure Arc",
        "The concept of infrastructure as code (IaC)",
        "Azure Resource Manager (ARM) and ARM templates",
        "The purpose of Azure Advisor",
        "Azure Service Health",
        "Azure Monitor, including Log Analytics, Monitor alerts, and Application Insights",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Associate: Microsoft Certified: Azure Administrator Associate (AZ-104)
// 100 minutes, scaled score 1-1000, minimum passing score 700.
// Domains: Identities and governance 20-25% / Storage 15-20% / Compute 20-25%
// / Virtual networking 15-20% / Monitor and maintain 10-15%.

export const AZURE_AZ104_TRACK: SeedTrack = {
  code: "AZ104",
  title: "Azure Administrator Associate Coach",
  description:
    "Microsoft Certified: Azure Administrator Associate (AZ-104): implementing, managing, and monitoring an Azure environment -- identities and governance, storage, compute, virtual networking, and day-to-day monitoring and recovery.",
  trackType: "certification",
  subcategorySlug: "it-certifications",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-administrator/",
  sourceVerifiedAt: VERIFIED_AT,
  credential: {
    ...AZURE_PROVIDER,
    credentialSlug: "azure-administrator",
    credentialName: "Microsoft Certified: Azure Administrator Associate",
    credentialUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-administrator/",
    examCode: "AZ-104",
    status: "active",
    officialObjectivesUrl: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-104",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "Familiarity with operating systems, networking, servers, and virtualization; experience with PowerShell, Azure CLI, the Azure portal, Azure Resource Manager templates or Bicep files, and Microsoft Entra ID.",
    durationMinutes: 100,
    questionFormat:
      "Microsoft does not publish an exact question count for AZ-104; the exam may include interactive item types",
    passingScorePolicy: "Scaled score 1-1000; minimum passing score 700",
  },
  units: [
    {
      title: "Manage Azure Identities and Governance",
      weight: 23,
      gate: "Given an identity, access, or governance scenario, name the specific Entra ID or Azure Policy/subscription control that applies -- not just 'set a permission'.",
      objectives: [
        "Creating Microsoft Entra users and groups",
        "Managing user and group properties",
        "Managing licenses in Microsoft Entra ID",
        "Managing external (guest) users",
        "Configuring self-service password reset (SSPR)",
        "Working with built-in Azure roles",
        "Assigning roles at different scopes",
        "Interpreting access assignments",
        "Implementing and managing Azure Policy",
        "Configuring resource locks",
        "Applying and managing tags on resources",
        "Managing resource groups",
        "Managing subscriptions",
        "Managing costs with alerts, budgets, and Azure Advisor recommendations",
        "Configuring management groups",
      ],
    },
    {
      title: "Implement and Manage Storage",
      weight: 18,
      gate: "Given a storage access, redundancy, or lifecycle requirement, name the specific Azure Storage feature that satisfies it and how it differs from a similarly-named alternative.",
      objectives: [
        "Configuring Azure Storage firewalls and virtual network rules",
        "Creating and using shared access signature (SAS) tokens",
        "Configuring stored access policies",
        "Managing storage account access keys",
        "Configuring identity-based access for Azure Files",
        "Creating and configuring storage accounts",
        "Configuring Azure Storage redundancy options",
        "Configuring object replication",
        "Configuring storage account encryption",
        "Managing data with Azure Storage Explorer and AzCopy",
        "Creating and configuring a file share in Azure Files",
        "Creating and configuring a container in Azure Blob Storage",
        "Configuring storage tiers",
        "Configuring soft delete for blobs and containers",
        "Configuring snapshots and soft delete for Azure Files",
        "Configuring blob lifecycle management",
        "Configuring blob versioning",
      ],
    },
    {
      title: "Deploy and Manage Azure Compute Resources",
      weight: 23,
      gate: "Given a workload, name the specific compute option (VM, Scale Set, container, or App Service) and the exact ARM/Bicep or portal step that provisions or configures it -- not just 'deploy it'.",
      objectives: [
        "Interpreting an Azure Resource Manager template or a Bicep file",
        "Modifying an existing Azure Resource Manager template",
        "Modifying an existing Bicep file",
        "Deploying resources with an Azure Resource Manager template or a Bicep file",
        "Exporting a deployment as an ARM template, or converting an ARM template to Bicep",
        "Creating a virtual machine",
        "Configuring encryption at host for Azure virtual machines",
        "Moving a virtual machine to another resource group, subscription, or region",
        "Managing virtual machine sizes",
        "Managing virtual machine disks",
        "Deploying virtual machines to availability zones and availability sets",
        "Deploying and configuring Azure Virtual Machine Scale Sets",
        "Creating and managing an Azure Container Registry",
        "Provisioning a container with Azure Container Instances",
        "Provisioning a container with Azure Container Apps",
        "Managing sizing and scaling for Azure Container Instances and Azure Container Apps",
        "Provisioning an App Service plan",
        "Configuring scaling for an App Service plan",
        "Creating an App Service",
        "Configuring certificates and Transport Layer Security (TLS) for an App Service",
        "Mapping an existing custom DNS name to an App Service",
        "Configuring backup for an App Service",
        "Configuring networking settings for an App Service",
        "Configuring deployment slots for an App Service",
      ],
    },
    {
      title: "Implement and Manage Virtual Networking",
      weight: 18,
      gate: "Given a connectivity or network-security requirement, name the specific virtual networking control (NSG, peering, Bastion, load balancer) that applies and what it would actually block or route.",
      objectives: [
        "Creating and configuring virtual networks and subnets",
        "Creating and configuring virtual network peering",
        "Configuring public IP addresses",
        "Configuring user-defined routes",
        "Troubleshooting network connectivity",
        "Creating and configuring network security groups (NSGs) and application security groups",
        "Evaluating effective security rules in NSGs",
        "Implementing Azure Bastion",
        "Configuring service endpoints for Azure platform as a service (PaaS)",
        "Configuring private endpoints for Azure PaaS",
        "Configuring Azure DNS",
        "Configuring an internal or public load balancer",
        "Troubleshooting load balancing",
      ],
    },
    {
      title: "Monitor and Maintain Azure Resources",
      weight: 12,
      gate: "Given a monitoring or disaster-recovery scenario, name the specific Azure Monitor or Azure Backup/Site Recovery capability that surfaces or restores what's needed.",
      objectives: [
        "Interpreting metrics in Azure Monitor",
        "Configuring log settings in Azure Monitor",
        "Querying and analyzing logs in Azure Monitor",
        "Setting up alert rules, action groups, and alert processing rules in Azure Monitor",
        "Configuring and interpreting monitoring of virtual machines, storage accounts, and networks with Azure Monitor Insights",
        "Using Azure Network Watcher and Connection Monitor",
        "Creating a Recovery Services vault",
        "Creating an Azure Backup vault",
        "Creating and configuring a backup policy",
        "Performing backup and restore operations with Azure Backup",
        "Configuring Azure Site Recovery for Azure resources",
        "Performing a failover to a secondary region with Site Recovery",
        "Configuring and interpreting reports and alerts for backups",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Expert: Microsoft Certified: Azure Solutions Architect Expert (AZ-305)
// Passing score 700; Microsoft does not publish exam duration or question
// count on the AZ-305 certification or exam pages. Requires the Azure
// Administrator Associate certification as a prerequisite.
// Domains: Identity/governance/monitoring 25-30% / Data storage 20-25% /
// Business continuity 15-20% / Infrastructure 30-35%.

export const AZURE_AZ305_TRACK: SeedTrack = {
  code: "AZ305",
  title: "Azure Solutions Architect Expert Coach",
  description:
    "Microsoft Certified: Azure Solutions Architect Expert (AZ-305): translating business requirements into Azure designs across identity/governance/monitoring, data storage, business continuity, and infrastructure -- aligned to the Well-Architected Framework and Cloud Adoption Framework. Requires the Azure Administrator Associate certification first.",
  trackType: "certification",
  subcategorySlug: "it-certifications",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-solutions-architect/",
  sourceVerifiedAt: VERIFIED_AT,
  credential: {
    ...AZURE_PROVIDER,
    credentialSlug: "azure-solutions-architect-expert",
    credentialName: "Microsoft Certified: Azure Solutions Architect Expert",
    credentialUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-solutions-architect/",
    examCode: "AZ-305",
    status: "active",
    officialObjectivesUrl: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-305",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "Requires the Azure Administrator Associate certification. Advanced experience with networking, virtualization, identity, security, business continuity, disaster recovery, data platforms, governance, Azure administration, Azure development, and DevOps processes.",
    questionFormat:
      "Microsoft does not publish an exact question count for AZ-305, or the exam duration, on its AZ-305 certification/exam pages",
    passingScorePolicy: "Minimum passing score 700",
  },
  units: [
    {
      title: "Design Identity, Governance, and Monitoring Solutions",
      weight: 28,
      gate: "Given a business requirement, recommend the specific Azure identity, governance, or monitoring solution that satisfies it -- and say why a plausible alternative falls short -- not just name a service.",
      objectives: [
        "Recommending a logging solution",
        "Recommending a solution for routing logs",
        "Recommending a monitoring solution",
        "Recommending an authentication solution",
        "Recommending an identity management solution",
        "Recommending a solution for authorizing access to Azure resources",
        "Recommending a solution for authorizing access to on-premises resources",
        "Recommending a solution to manage secrets, certificates, and keys",
        "Recommending a structure for management groups, subscriptions, and resource groups, plus a resource-tagging strategy",
        "Recommending a solution for managing compliance",
        "Recommending a solution for identity governance",
      ],
    },
    {
      title: "Design Data Storage Solutions",
      weight: 23,
      gate: "Given a data workload's structure, scale, and durability requirements, recommend the specific Azure data storage solution that fits -- and the tradeoff it makes against the next-best option.",
      objectives: [
        "Recommending a solution for storing relational data",
        "Recommending a database service tier and compute tier",
        "Recommending a solution for database scalability",
        "Recommending a solution for data protection",
        "Recommending a solution for storing semi-structured data",
        "Recommending a solution for storing unstructured data",
        "Recommending a data storage solution that balances features, performance, and cost",
        "Recommending a data solution for protection and durability",
        "Recommending a solution for data integration",
        "Recommending a solution for data analysis",
      ],
    },
    {
      title: "Design Business Continuity Solutions",
      weight: 18,
      gate: "Given a stated recovery objective (RPO/RTO) or availability target, recommend the specific backup, recovery, or high-availability solution that meets it.",
      objectives: [
        "Recommending a recovery solution for Azure and hybrid workloads that meets stated recovery objectives",
        "Recommending a backup and recovery solution for compute",
        "Recommending a backup and recovery solution for databases",
        "Recommending a backup and recovery solution for unstructured data",
        "Recommending a high availability solution for compute",
        "Recommending a high availability solution for relational data",
        "Recommending a high availability solution for semi-structured and unstructured data",
      ],
    },
    {
      title: "Design Infrastructure Solutions",
      weight: 33,
      gate: "Given a workload's compute, application-architecture, migration, or network requirement, recommend the specific Azure solution that fits -- not a generic 'move it to Azure' answer.",
      objectives: [
        "Specifying compute-solution components based on workload requirements",
        "Recommending a virtual machine-based solution",
        "Recommending a container-based solution",
        "Recommending a serverless-based solution",
        "Recommending a compute solution for batch processing",
        "Recommending a messaging architecture",
        "Recommending an event-driven architecture",
        "Recommending a solution for API integration",
        "Recommending a caching solution for applications",
        "Recommending an application configuration management solution",
        "Recommending an automated deployment solution for applications",
        "Evaluating a migration solution using the Microsoft Cloud Adoption Framework for Azure",
        "Evaluating on-premises servers, data, and applications for migration",
        "Recommending a solution for migrating workloads to infrastructure as a service (IaaS) and platform as a service (PaaS)",
        "Recommending a solution for migrating databases",
        "Recommending a solution for migrating unstructured data",
        "Recommending a connectivity solution that connects Azure resources to the internet",
        "Recommending a connectivity solution that connects Azure resources to on-premises networks",
        "Recommending a solution to optimize network performance",
        "Recommending a solution to optimize network security",
        "Recommending a load-balancing and routing solution",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Foundational: Microsoft Certified: Azure AI Fundamentals (AI-901)
// Passing score 700; Microsoft does not publish exam duration or question
// count on the AI-901 certification or exam pages.
// Domains: Identify AI concepts and capabilities 40-45% / Implement AI
// solutions by using Microsoft Foundry 55-60%.
//
// This certification's exam retired AI-900 (retired 2026-06-30) in favor of
// AI-901, updated 2026-04-15 -- not just a version bump. The old AI-900
// domain structure (separate ML/computer-vision/NLP/generative-AI domains)
// is gone; AI-901 is organized around Microsoft Foundry as the single
// implementation surface for generative AI, vision, speech, and information
// extraction. Do not author this track's objectives from AI-900 material.

export const AZURE_AI901_TRACK: SeedTrack = {
  code: "AI901",
  title: "Azure AI Fundamentals Coach",
  description:
    "Microsoft Certified: Azure AI Fundamentals (AI-901): core AI/ML concepts and responsible AI principles, then building generative AI, vision, speech, and information-extraction solutions with Microsoft Foundry.",
  trackType: "certification",
  subcategorySlug: "it-certifications",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-fundamentals/",
  sourceVerifiedAt: VERIFIED_AT,
  credential: {
    ...AZURE_PROVIDER,
    credentialSlug: "azure-ai-fundamentals",
    credentialName: "Microsoft Certified: Azure AI Fundamentals",
    credentialUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-fundamentals/",
    examCode: "AI-901",
    status: "active",
    officialObjectivesUrl: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/ai-901",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "No prerequisites; benefits from familiarity with Python syntax and programming techniques, Azure resources, and REST APIs/SDKs/CLIs.",
    questionFormat:
      "Microsoft does not publish an exact question count for AI-901, or the exam duration, on its AI-901 certification/exam pages",
    passingScorePolicy: "Minimum passing score 700",
  },
  units: [
    {
      title: "AI Concepts and Capabilities",
      weight: 43,
      gate: "Given an AI scenario, name the specific responsible-AI consideration or workload category at play -- not a generic 'AI can help with that'.",
      objectives: [
        "Considerations for fairness in an AI solution",
        "Considerations for reliability and safety in an AI solution",
        "Considerations for privacy and security in an AI solution",
        "Considerations for inclusiveness in an AI solution",
        "Considerations for transparency in an AI solution",
        "Considerations for accountability in an AI solution",
        "How generative AI models work",
        "Identifying an appropriate AI model based on its capabilities",
        "Identifying appropriate model deployment options and configuration parameters",
        "Scenarios for common AI workloads, including generative and agentic AI, text analysis, speech, computer vision, and information extraction",
        "Common text analysis techniques: keyword extraction, entity detection, sentiment analysis, and summarization",
        "Features and capabilities of speech recognition and speech synthesis",
        "Features and capabilities of computer vision and image-generation models",
        "Techniques to extract information from text, images, audio, and video",
      ],
    },
    {
      title: "Implementing AI Solutions with Microsoft Foundry",
      weight: 58,
      gate: "Given a task -- a chat agent, a vision or speech feature, an extraction pipeline -- name the specific Foundry capability that builds it and how a lightweight client would call it.",
      objectives: [
        "Writing effective system and user prompts for generative AI models",
        "Deploying a model and interacting with it in the Foundry portal",
        "Building a lightweight chat client application with the Foundry SDK",
        "Creating and testing a single-agent solution in the Foundry portal",
        "Building a lightweight client application for an agent",
        "Building a lightweight application that includes text analysis",
        "Responding to spoken prompts using a deployed multimodal model",
        "Building a lightweight application using Azure Speech in Foundry Tools",
        "Interpreting visual input in prompts using a deployed multimodal model",
        "Creating new visual outputs using generative models",
        "Building a lightweight application that includes vision capabilities",
        "Extracting information from documents and forms using Azure Content Understanding in Foundry Tools",
        "Extracting information from images using Content Understanding",
        "Extracting information from audio and video using Content Understanding",
        "Building a lightweight application with information-extraction capabilities using Content Understanding",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Foundational: Microsoft Certified: Azure Data Fundamentals (DP-900)
// 45 minutes, minimum passing score 700.
// Domains: Core data concepts 25-30% / Relational data 20-25% /
// Non-relational data 15-20% / Analytics workload 25-30%.

export const AZURE_DP900_TRACK: SeedTrack = {
  code: "DP900",
  title: "Azure Data Fundamentals Coach",
  description:
    "Microsoft Certified: Azure Data Fundamentals (DP-900): core relational and non-relational data concepts, Azure's data services for each, and the building blocks of an analytics workload -- ingestion, analytical stores, real-time analytics, and Power BI visualization.",
  trackType: "certification",
  subcategorySlug: "it-certifications",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-data-fundamentals/",
  sourceVerifiedAt: VERIFIED_AT,
  credential: {
    ...AZURE_PROVIDER,
    credentialSlug: "azure-data-fundamentals",
    credentialName: "Microsoft Certified: Azure Data Fundamentals",
    credentialUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-data-fundamentals/",
    examCode: "DP-900",
    status: "active",
    officialObjectivesUrl: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/dp-900",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "No prerequisites; familiarity with relational and non-relational data concepts and with transactional versus analytical data workloads is helpful.",
    durationMinutes: 45,
    questionFormat:
      "Microsoft does not publish an exact question count for DP-900; questions are multiple choice and multiple response",
    passingScorePolicy: "Minimum passing score 700",
  },
  units: [
    {
      title: "Core Data Concepts",
      weight: 28,
      gate: "Given a dataset or workload description, name whether it's structured/semi-structured/unstructured and transactional/analytical -- and which data role owns it -- not just 'it's data'.",
      objectives: [
        "Features of structured data",
        "Features of semi-structured data",
        "Features of unstructured data",
        "Common formats for data files",
        "Features of common data stores, including databases",
        "Identifying Azure datastores for common use cases",
        "Features of transactional workloads",
        "Features of analytical workloads",
        "Responsibilities of database administrators",
        "Responsibilities of data engineers",
        "Responsibilities of data analysts",
      ],
    },
    {
      title: "Relational Data on Azure",
      weight: 23,
      gate: "Given a relational-data requirement, name the specific Azure SQL product or open-source database service that fits -- and the SQL concept (normalization, a given statement type, a database object) behind it.",
      objectives: [
        "Features of relational data",
        "Normalization and why it's used",
        "Common SQL statements",
        "Common database objects",
        "The Azure SQL family of products: Azure SQL Database, Azure SQL Managed Instance, and SQL Server on Azure Virtual Machines",
        "Azure database services for open-source database systems",
      ],
    },
    {
      title: "Non-Relational Data on Azure",
      weight: 18,
      gate: "Given a non-relational data scenario, name the specific Azure Storage or Cosmos DB feature/API that fits -- not just 'use Cosmos DB'.",
      objectives: [
        "Features of Azure Blob storage",
        "Features of Azure Files",
        "Features of Azure Table storage",
        "Use cases for Azure Cosmos DB",
        "Azure Cosmos DB APIs",
      ],
    },
    {
      title: "Analytics Workload on Azure",
      weight: 28,
      gate: "Given an analytics scenario, name the specific ingestion, storage, or visualization component -- including whether it's batch or streaming -- that fits, and how Power BI would present the result.",
      objectives: [
        "Considerations for data ingestion and processing",
        "Options for analytical data stores",
        "Microsoft cloud services for large-scale analytics, including Azure Databricks and Microsoft Fabric",
        "The difference between batch and streaming data",
        "Microsoft cloud services for real-time analytics",
        "Capabilities of Power BI",
        "Features of data models in Power BI",
        "Choosing appropriate visualizations for data",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Associate: Microsoft Certified: Azure Network Engineer Associate (AZ-700)
// 100 minutes, minimum passing score 700.
// Domains: Core networking infrastructure 25-30% / Connectivity services
// 20-25% / Application delivery services 15-20% / Private access 10-15% /
// Network security services 15-20%.

export const AZURE_AZ700_TRACK: SeedTrack = {
  code: "AZ700",
  title: "Azure Network Engineer Associate Coach",
  description:
    "Microsoft Certified: Azure Network Engineer Associate (AZ-700): designing and implementing Azure networking end to end -- IP addressing and DNS, VNet routing and monitoring, VPN/ExpressRoute/Virtual WAN connectivity, load balancing and Front Door, private access, and network security (NSGs, Azure Firewall, WAF).",
  trackType: "certification",
  subcategorySlug: "it-certifications",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-network-engineer-associate/",
  sourceVerifiedAt: VERIFIED_AT,
  credential: {
    ...AZURE_PROVIDER,
    credentialSlug: "azure-network-engineer-associate",
    credentialName: "Microsoft Certified: Azure Network Engineer Associate",
    credentialUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-network-engineer-associate/",
    examCode: "AZ-700",
    status: "active",
    officialObjectivesUrl: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-700",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "Experience creating and managing compute, storage, and networking resources in Azure; understanding of networking fundamentals such as name resolution, network protocols, and network address management.",
    durationMinutes: 100,
    questionFormat: "Microsoft does not publish an exact question count for AZ-700",
    passingScorePolicy: "Minimum passing score 700",
  },
  units: [
    {
      title: "Design and Implement Core Networking Infrastructure",
      weight: 28,
      gate: "Given an IP addressing, DNS, routing, or monitoring requirement, name the specific Azure networking control that fits -- not a generic 'set up the VNet'.",
      objectives: [
        "Planning network segmentation and address spaces",
        "Creating a virtual network (VNet)",
        "Planning and configuring subnetting for services -- virtual network gateways, private endpoints, service endpoints, firewalls, application gateways, VNet-integrated platform services, and Azure Bastion",
        "Planning and configuring subnet delegation",
        "Planning and configuring shared versus dedicated subnets",
        "Creating a Public IP Prefix, and choosing when to use one",
        "Planning and implementing a custom IP address prefix (bring your own IP)",
        "Creating and associating public IP addresses with resources",
        "Designing name resolution inside a VNet",
        "Configuring DNS settings for a VNet",
        "Designing public DNS zones",
        "Designing private DNS zones",
        "Configuring public and private DNS zones",
        "Linking a private DNS zone to a VNet",
        "Designing and implementing Azure DNS Private Resolver",
        "Designing service chaining, including gateway transit",
        "Implementing VNet peering",
        "Implementing and managing virtual network connectivity with Azure Virtual Network Manager",
        "Designing and implementing user-defined routes (UDRs)",
        "Associating a route table with a subnet",
        "Configuring forced tunneling",
        "Diagnosing and resolving routing issues",
        "Designing and implementing Azure Route Server",
        "Identifying use cases for Azure NAT Gateway, and implementing it",
        "Configuring monitoring, network diagnostics, and logs in Azure Network Watcher",
        "Monitoring and troubleshooting network health and networks with Azure Network Watcher and Azure Monitor for Networks",
        "Activating and monitoring DDoS protection",
        "Evaluating network security recommendations from Microsoft Defender for Cloud, via Secure Score and attack path analysis",
        "Identifying network resources with Cloud Security Explorer in Microsoft Defender for Cloud",
      ],
    },
    {
      title: "Design, Implement, and Manage Connectivity Services",
      weight: 23,
      gate: "Given a hybrid-connectivity requirement, name the specific VPN, ExpressRoute, or Virtual WAN option that fits -- and the SKU/tier decision behind it -- not just 'connect it to Azure'.",
      objectives: [
        "Designing a site-to-site VPN connection, including for high availability",
        "Selecting a virtual network gateway SKU for site-to-site VPN requirements",
        "Implementing a site-to-site VPN connection",
        "Identifying when to use a policy-based versus route-based VPN connection",
        "Creating and configuring a local network gateway",
        "Creating and configuring an IPsec/Internet Key Exchange (IKE) policy",
        "Creating and configuring a virtual network gateway",
        "Diagnosing and resolving virtual network gateway connectivity issues",
        "Implementing Azure Extended Network",
        "Selecting a virtual network gateway SKU for point-to-site VPN requirements",
        "Selecting and configuring a tunnel type",
        "Selecting an authentication method for point-to-site VPN",
        "Configuring RADIUS authentication",
        "Configuring authentication with Microsoft Entra ID",
        "Implementing a VPN client configuration file",
        "Diagnosing and resolving client-side and authentication issues",
        "Specifying Azure requirements for Always On VPN",
        "Specifying Azure requirements for Azure Network Adapter",
        "Selecting an ExpressRoute connectivity model",
        "Selecting an ExpressRoute SKU and tier",
        "Designing and implementing ExpressRoute for cross-region connectivity, redundancy, and disaster recovery",
        "Designing and implementing ExpressRoute options -- Global Reach, FastPath, and ExpressRoute Direct",
        "Choosing between Azure private peering, Microsoft peering, or both",
        "Configuring Azure private peering",
        "Configuring Microsoft peering",
        "Creating and configuring an ExpressRoute gateway",
        "Connecting a virtual network to an ExpressRoute circuit",
        "Recommending a route advertisement configuration",
        "Configuring encryption over ExpressRoute",
        "Implementing Bidirectional Forwarding Detection",
        "Diagnosing and resolving ExpressRoute connection issues",
        "Selecting a Virtual WAN SKU",
        "Designing a Virtual WAN architecture, including types and services",
        "Creating a virtual hub in Virtual WAN",
        "Choosing a scale unit for each gateway type",
        "Deploying a gateway into a virtual hub",
        "Configuring virtual hub routing",
        "Integrating a virtual hub with a third-party network virtual appliance (NVA) for cloud connectivity",
      ],
    },
    {
      title: "Design and Implement Application Delivery Services",
      weight: 18,
      gate: "Given a traffic-distribution requirement, name the specific Azure Load Balancer, Application Gateway, or Front Door feature that fits -- and why the other two don't.",
      objectives: [
        "Mapping requirements to Azure Load Balancer features and capabilities",
        "Identifying use cases for Azure Load Balancer",
        "Choosing an Azure Load Balancer SKU and tier",
        "Choosing between public and internal load balancers",
        "Choosing between regional and cross-region load balancers",
        "Creating and configuring an Azure Load Balancer",
        "Implementing Azure Traffic Manager",
        "Implementing Gateway Load Balancer",
        "Implementing a load balancing rule",
        "Creating and configuring inbound NAT rules",
        "Creating and configuring explicit outbound rules, including source network address translation (SNAT)",
        "Mapping requirements to Azure Application Gateway features and capabilities",
        "Identifying use cases for Azure Application Gateway",
        "Choosing between manual and autoscale for Application Gateway",
        "Creating a backend pool",
        "Configuring health probes",
        "Configuring listeners",
        "Configuring routing rules",
        "Configuring HTTP settings",
        "Configuring Transport Layer Security (TLS) on Application Gateway",
        "Configuring rewrite rule sets",
        "Mapping requirements to Azure Front Door features and capabilities",
        "Identifying use cases for Azure Front Door",
        "Choosing a Front Door tier",
        "Configuring Azure Front Door routing, origins, and endpoints",
        "Configuring TLS termination and end-to-end TLS encryption on Front Door",
        "Configuring caching",
        "Configuring traffic acceleration",
        "Implementing rules, URL rewrite, and URL redirect",
        "Securing an origin with Azure Private Link in Azure Front Door",
      ],
    },
    {
      title: "Design and Implement Private Access to Azure Services",
      weight: 13,
      gate: "Given a requirement to keep traffic off the public internet, name whether a private endpoint or a service endpoint fits, and why.",
      objectives: [
        "Planning private endpoints",
        "Creating private endpoints",
        "Configuring access to private endpoints",
        "Creating a Private Link service",
        "Integrating Private Link and Private Endpoint with DNS",
        "Integrating a Private Link service with on-premises clients",
        "Choosing when to use a service endpoint",
        "Creating service endpoints",
        "Configuring service endpoint policies",
        "Configuring access to service endpoints",
      ],
    },
    {
      title: "Design and Implement Azure Network Security Services",
      weight: 18,
      gate: "Given a network-security requirement, name the specific NSG, Azure Firewall, or WAF control that fits, and what traffic it would actually allow or block.",
      objectives: [
        "Creating a network security group (NSG)",
        "Associating an NSG to a subnet or network interface",
        "Creating an application security group (ASG)",
        "Associating an ASG to a network interface",
        "Creating and configuring NSG inbound and outbound security rules",
        "Implementing virtual network flow logs",
        "Interpreting virtual network flow logs",
        "Verifying IP flow",
        "Configuring an NSG for remote server administration, including Azure Bastion",
        "Implementing and managing virtual network security with Azure Virtual Network Manager",
        "Mapping requirements to Azure Firewall features and capabilities",
        "Selecting an Azure Firewall SKU",
        "Designing an Azure Firewall deployment",
        "Creating and implementing an Azure Firewall deployment",
        "Configuring Azure Firewall rules",
        "Creating and implementing Azure Firewall Manager policies",
        "Creating a secure hub by deploying Azure Firewall inside a Virtual WAN hub",
        "Mapping requirements to Web Application Firewall (WAF) features and capabilities",
        "Designing a WAF deployment",
        "Configuring detection or prevention mode",
        "Configuring WAF rule sets on Azure Front Door",
        "Configuring WAF rule sets on Application Gateway",
        "Implementing a WAF policy",
        "Associating a WAF policy",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Specialty: Microsoft Certified: Azure Virtual Desktop Specialty (AZ-140)
// 100 minutes, minimum passing score 700.
// Domains: Plan and implement an AVD infrastructure 40-45% / Plan and
// implement identity and security 15-20% / Plan and implement user
// environments and apps 20-25% / Monitor and maintain an AVD infrastructure
// 10-15%.

export const AZURE_AZ140_TRACK: SeedTrack = {
  code: "AZ140",
  title: "Azure Virtual Desktop Specialty Coach",
  description:
    "Microsoft Certified: Azure Virtual Desktop Specialty (AZ-140): planning and implementing an Azure Virtual Desktop infrastructure -- networking, storage, host pools, and session host images -- plus identity and security, user environments and app delivery (FSLogix, App attach), and ongoing monitoring, backup, and disaster recovery.",
  trackType: "certification",
  subcategorySlug: "it-certifications",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-virtual-desktop-specialty/",
  sourceVerifiedAt: VERIFIED_AT,
  credential: {
    ...AZURE_PROVIDER,
    credentialSlug: "azure-virtual-desktop-specialty",
    credentialName: "Microsoft Certified: Azure Virtual Desktop Specialty",
    credentialUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-virtual-desktop-specialty/",
    examCode: "AZ-140",
    status: "active",
    officialObjectivesUrl: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-140",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "Server or desktop administrator experience designing, implementing, managing, and maintaining Azure Virtual Desktop experiences and remote apps, working closely with Azure administrators, Azure architects, Microsoft 365 administrators, and Azure security engineers; experience with Azure compute, networking, identity, storage, and resiliency.",
    durationMinutes: 100,
    questionFormat: "Microsoft does not publish an exact question count for AZ-140",
    passingScorePolicy: "Minimum passing score 700",
  },
  units: [
    {
      title: "Plan and Implement an Azure Virtual Desktop Infrastructure",
      weight: 43,
      gate: "Given an AVD networking, storage, host-pool, or image requirement, name the specific control or workflow that fits -- not a generic 'deploy AVD'.",
      objectives: [
        "Assessing network capacity and speed requirements for Azure Virtual Desktop",
        "Designing network configuration for session hosts to meet AVD requirements",
        "Planning and implementing RDP Shortpath, RDP Multipath, and quality of service (QoS) policies",
        "Planning and implementing an Azure Private Link solution for Azure Virtual Desktop",
        "Monitoring and troubleshooting network connectivity",
        "Planning storage for Azure Virtual Desktop user data",
        "Implementing storage for FSLogix components",
        "Implementing storage accounts for Azure Virtual Desktop",
        "Implementing file shares for Azure Virtual Desktop",
        "Implementing Azure NetApp Files for Azure Virtual Desktop",
        "Recommending resource groups, subscriptions, and management groups for Azure Virtual Desktop resources",
        "Recommending an operating system for Azure Virtual Desktop session hosts",
        "Recommending a licensing model for Azure Virtual Desktop based on requirements",
        "Planning a host pool architecture",
        "Designing an Azure Virtual Desktop configuration for performance requirements",
        "Designing an Azure Virtual Desktop configuration for Azure VM capacity requirements",
        "Creating host pools and session hosts using the Azure portal",
        "Automating creation of Azure Virtual Desktop hosts and host pools with PowerShell, Azure CLI, ARM templates, and Bicep files",
        "Configuring host pool and session host settings",
        "Configuring licensing for session hosts, including Windows client access eligibility and RDS Client Access License requirements for Windows Server",
        "Creating a session host image manually",
        "Creating a session host image using Azure VM Image Builder",
        "Modifying a session host image",
        "Planning and implementing lifecycle management for session host images",
        "Applying OS and application updates to a session host image",
        "Creating a session host from a custom image",
        "Planning and implementing image storage, including Azure Compute Gallery",
      ],
    },
    {
      title: "Plan and Implement Identity and Security",
      weight: 18,
      gate: "Given an AVD identity or security requirement, name the specific identity scenario or protection control that fits, not just 'secure it'.",
      objectives: [
        "Selecting an identity scenario for Azure Virtual Desktop -- Active Directory Domain Services, Microsoft Entra ID, and Microsoft Entra Domain Services",
        "Specifying requirements to configure the AVD session host for an identity scenario",
        "Planning and implementing Azure role-based access control (Azure RBAC) for Azure Virtual Desktop",
        "Planning and implementing Microsoft Entra Conditional Access policies for connections to Azure Virtual Desktop",
        "Planning and implementing authentication options in Azure Virtual Desktop, including passwordless, smart card, and multifactor authentication",
        "Managing roles, groups, and rights assignments on Azure Virtual Desktop session hosts",
        "Configuring Microsoft Entra single sign-on",
        "Planning, implementing, and managing security for Azure Virtual Desktop session hosts using Microsoft Defender for Cloud",
        "Configuring session host protection using Microsoft Defender Antivirus",
        "Configuring session host protection using Microsoft Defender for Endpoint, including onboarding and scanning options",
        "Implementing and managing network security for connections to Azure Virtual Desktop, including user-defined routes, network security groups, and Azure Firewall",
        "Configuring Azure Bastion or just-in-time VM access for administrative access to session hosts",
        "Planning and implementing Windows threat protection features on Azure Virtual Desktop session hosts, including App Control for Business and Controlled Folder Access",
        "Planning for and implementing Azure confidential VMs and Trusted Launch security features for Azure Virtual Desktop session hosts",
      ],
    },
    {
      title: "Plan and Implement User Environments and Apps",
      weight: 23,
      gate: "Given a user-profile or app-delivery requirement, name the specific FSLogix, client, or App attach configuration that fits.",
      objectives: [
        "Recommending an FSLogix configuration",
        "Configuring FSLogix Profile Containers",
        "Configuring FSLogix ODFC containers",
        "Configuring FSLogix Cloud Cache",
        "Implementing FSLogix application masking",
        "Choosing an Azure Virtual Desktop client",
        "Choosing a deployment method for the client",
        "Deploying and troubleshooting Azure Virtual Desktop clients",
        "Configuring device redirection",
        "Configuring multimedia redirection",
        "Configuring printing and Universal Print",
        "Configuring user settings through Microsoft Intune policies or Group Policy",
        "Configuring Remote Desktop Protocol (RDP) properties on a host pool",
        "Configuring session timeout properties",
        "Implementing the Start VM on Connect feature",
        "Assigning and unassigning personal desktops to users",
        "Choosing a method for deploying an app to Azure Virtual Desktop",
        "Creating and configuring an application group",
        "Assigning users to application groups",
        "Publishing an application as a RemoteApp",
        "Implementing and managing Microsoft 365 Apps on Azure Virtual Desktop session hosts",
        "Implementing and managing OneDrive, including multisession environments",
        "Implementing and managing Microsoft Teams, including the Remote Desktop WebRTC Redirector Service",
        "Implementing and managing browsers for Azure Virtual Desktop sessions",
        "Configuring dynamic application delivery using App attach",
        "Creating an application package for App attach",
      ],
    },
    {
      title: "Monitor and Maintain an Azure Virtual Desktop Infrastructure",
      weight: 13,
      gate: "Given an ongoing-operations requirement, name the specific monitoring, autoscaling, backup, or DR control that fits, not just 'keep an eye on it'.",
      objectives: [
        "Configuring log collection and analysis for Azure Virtual Desktop session hosts",
        "Monitoring Azure Virtual Desktop using Azure Monitor",
        "Customizing Azure Monitor workbooks for Azure Virtual Desktop Insights",
        "Optimizing session host capacity and performance",
        "Implementing autoscaling in host pools",
        "Monitoring and managing active sessions and application groups",
        "Recommending an update strategy for session hosts",
        "Planning and implementing a disaster recovery plan for Azure Virtual Desktop",
        "Planning for multi-region implementation",
        "Designing and implementing a backup strategy for Azure Virtual Desktop",
        "Configuring backup and restore for FSLogix user profiles, personal desktops, and images",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Associate: Microsoft Certified: Azure Database Administrator Associate (DP-300)
// 100 minutes, minimum passing score 700.
// Domains: Plan and implement data platform resources 15-20% / Implement a
// secure environment 20-25% / Monitor, configure, and optimize database
// resources 20-25% / Configure and manage automation of tasks 15-20% /
// Plan and configure an HA/DR environment 20-25%.

export const AZURE_DP300_TRACK: SeedTrack = {
  code: "DP300",
  title: "Azure Database Administrator Associate Coach",
  description:
    "Microsoft Certified: Azure Database Administrator Associate (DP-300): administering Azure SQL Database, Azure SQL Managed Instance, and SQL Server on Azure VMs -- deployment and migration, authentication and data protection, performance monitoring and tuning, task automation, and high availability/disaster recovery.",
  trackType: "certification",
  subcategorySlug: "it-certifications",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-database-administrator-associate/",
  sourceVerifiedAt: VERIFIED_AT,
  credential: {
    ...AZURE_PROVIDER,
    credentialSlug: "azure-database-administrator-associate",
    credentialName: "Microsoft Certified: Azure Database Administrator Associate",
    credentialUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-database-administrator-associate/",
    examCode: "DP-300",
    status: "active",
    officialObjectivesUrl: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/dp-300",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "Subject matter expertise building database solutions on Azure SQL services and SQL Server on-premises, including day-to-day operational management, availability, security, and performance monitoring/optimization using Transact-SQL and other administrative tools.",
    durationMinutes: 100,
    questionFormat: "Microsoft does not publish an exact question count for DP-300",
    passingScorePolicy: "Minimum passing score 700",
  },
  units: [
    {
      title: "Plan and Implement Data Platform Resources",
      weight: 18,
      gate: "Given an Azure SQL deployment, scaling, or migration requirement, name the specific offering or migration strategy that fits -- not a generic 'move it to Azure'.",
      objectives: [
        "Recommending a database offering based on specific requirements",
        "Choosing an automated deployment method",
        "Identifying use cases for Azure Arc-enabled SQL services",
        "Identifying use cases for Azure SQL Database in Microsoft Fabric",
        "Planning for table partitioning",
        "Recommending a database sharding solution",
        "Deploying database offerings on selected platforms",
        "Deploying hybrid SQL Server solutions",
        "Applying patches and updates for hybrid and infrastructure as a service (IaaS) deployments",
        "Configuring Azure SQL Database for scale and performance",
        "Configuring Azure SQL Managed Instance for scale and performance",
        "Configuring SQL Server on Azure Virtual Machines for scale and performance",
        "Configuring table partitioning",
        "Configuring data compression",
        "Evaluating requirements for a migration",
        "Evaluating offline versus online migration strategies",
        "Implementing an online migration strategy",
        "Implementing an offline migration strategy",
        "Implementing a migration to Azure",
        "Implementing a migration between Azure SQL services",
        "Implementing Azure SQL Managed Instance database copy and move",
        "Troubleshooting a migration",
      ],
    },
    {
      title: "Implement a Secure Environment",
      weight: 23,
      gate: "Given a database authentication, encryption, or compliance requirement, name the specific control that fits, not just 'lock it down'.",
      objectives: [
        "Configuring Microsoft Entra ID authentication for Azure SQL Database, Azure SQL Managed Instance, and SQL Server",
        "Configuring authentication for SQL on Azure VMs and Azure SQL Managed Instance",
        "Configuring security principals",
        "Creating users from Microsoft Entra identities",
        "Configuring database and object-level permissions using graphical tools",
        "Applying the principle of least privilege for all securables",
        "Troubleshooting authentication and authorization issues",
        "Managing authentication and authorization using T-SQL",
        "Implementing transparent data encryption (TDE)",
        "Implementing object-level encryption",
        "Configuring server- and database-level firewall rules",
        "Implementing Always Encrypted",
        "Implementing Always Encrypted with VBS enclaves",
        "Configuring private links and service endpoints",
        "Applying a data classification strategy",
        "Configuring server and database audits",
        "Implementing change data tracking",
        "Implementing dynamic data masking",
        "Implementing ledger in Azure SQL",
        "Implementing row-level security",
      ],
    },
    {
      title: "Monitor, Configure, and Optimize Database Resources",
      weight: 23,
      gate: "Given a performance-monitoring or tuning requirement, name the specific metric source or tuning control that fits, not just 'make it faster'.",
      objectives: [
        "Preparing an operational performance baseline",
        "Determining sources for performance metrics",
        "Interpreting performance metrics",
        "Configuring and monitoring activity and performance",
        "Monitoring using database watcher",
        "Monitoring using Extended Events",
        "Configuring Query Store",
        "Monitoring using Query Store",
        "Identifying and resolving session blocking",
        "Identifying performance issues using dynamic management views (DMVs)",
        "Identifying and implementing index changes for queries",
        "Recommending query construct modifications based on resource usage",
        "Reviewing execution plans",
        "Monitoring using Intelligent Insights",
        "Implementing index maintenance tasks",
        "Implementing statistics maintenance tasks",
        "Implementing database integrity checks",
        "Configuring database automatic tuning",
        "Configuring server settings for performance",
        "Configuring Resource Governor for performance",
        "Implementing database-scoped configuration",
        "Configuring compute and storage resources for scaling",
        "Identifying use cases for intelligent query processing (IQP) features",
      ],
    },
    {
      title: "Configure and Manage Automation of Tasks",
      weight: 18,
      gate: "Given a recurring database-operations requirement, name the specific automation tool (SQL Server Agent, ARM/Bicep, elastic jobs) that fits.",
      objectives: [
        "Managing schedules for regular maintenance jobs",
        "Configuring job alerts and notifications",
        "Troubleshooting SQL Server Agent jobs",
        "Automating deployment using Azure Resource Manager (ARM) and Bicep templates",
        "Automating deployment using Azure PowerShell",
        "Automating deployment using Azure CLI",
        "Monitoring and troubleshooting deployments",
        "Creating and configuring elastic jobs",
        "Creating and configuring database tasks using automation",
        "Configuring alerts and notifications on database tasks",
        "Troubleshooting automated database tasks",
      ],
    },
    {
      title: "Plan and Configure a High Availability and Disaster Recovery Environment",
      weight: 23,
      gate: "Given an RPO/RTO requirement, name the specific HA/DR configuration (geo-replication, availability groups, failover groups, log shipping) that fits, not just 'make it resilient'.",
      objectives: [
        "Recommending an HA/DR strategy based on Recovery Point Objective/Recovery Time Objective (RPO/RTO) requirements",
        "Evaluating HA/DR for hybrid deployments",
        "Evaluating Azure-specific HA/DR solutions",
        "Planning a testing procedure for an HA/DR solution",
        "Recommending a database backup and restore strategy",
        "Performing a database backup using native tools",
        "Performing a database restore using native tools",
        "Performing a database restore to a point in time",
        "Configuring long-term backup retention",
        "Backing up and restoring a database using T-SQL",
        "Backing up to and restoring from cloud storage",
        "Configuring active geo-replication",
        "Configuring Always On availability groups on SQL Managed Instance and Azure virtual machines",
        "Configuring failover groups",
        "Configuring Always On Failover Cluster Instances on Azure virtual machines",
        "Configuring log shipping",
        "Monitoring an HA/DR solution",
        "Troubleshooting an HA/DR solution",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Expert: Microsoft Certified: DevOps Engineer Expert (AZ-400)
// Minimum passing score 700; Microsoft does not publish an exam duration.
// Prerequisite: Azure Administrator Associate (AZ-104) certification -- the
// other listed path, Azure Developer Associate (AZ-204), is retired.
// Domains: Processes and communications 10-15% / Source control strategy
// 10-15% / Build and release pipelines 50-55% / Security and compliance
// 10-15% / Instrumentation strategy 5-10%.

export const AZURE_AZ400_TRACK: SeedTrack = {
  code: "AZ400",
  title: "Azure DevOps Engineer Expert Coach",
  description:
    "Microsoft Certified: DevOps Engineer Expert (AZ-400): designing and implementing Microsoft DevOps solutions across GitHub and Azure DevOps -- work-item flow and metrics, source control strategy, build/release pipelines, deployment strategies, infrastructure as code, security and compliance scanning, and instrumentation. Requires the Azure Administrator Associate certification.",
  trackType: "certification",
  subcategorySlug: "it-certifications",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://learn.microsoft.com/en-us/credentials/certifications/devops-engineer/",
  sourceVerifiedAt: VERIFIED_AT,
  credential: {
    ...AZURE_PROVIDER,
    credentialSlug: "devops-engineer-expert",
    credentialName: "Microsoft Certified: DevOps Engineer Expert",
    credentialUrl: "https://learn.microsoft.com/en-us/credentials/certifications/devops-engineer/",
    examCode: "AZ-400",
    status: "active",
    officialObjectivesUrl: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-400",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "Experience both administering and developing in Azure, with strong skills in at least one area, plus experience implementing both GitHub and Azure DevOps solutions; requires holding the Microsoft Certified: Azure Administrator Associate certification as a prerequisite.",
    questionFormat: "Microsoft does not publish an exact question count or duration for AZ-400",
    passingScorePolicy: "Minimum passing score 700",
  },
  units: [
    {
      title: "Design and Implement Processes and Communications",
      weight: 13,
      gate: "Given a work-tracking, metrics, or collaboration requirement, name the specific GitHub/Azure Boards integration or metric that fits, not just 'track it'.",
      objectives: [
        "Designing and implementing a structure for the flow of work, including GitHub Flow",
        "Designing and implementing a strategy for feedback cycles, including notifications and GitHub Issues",
        "Designing and implementing integration for tracking work, including GitHub projects, Azure Boards, and repositories",
        "Designing and implementing source, bug, and quality traceability",
        "Designing and implementing a dashboard for flow of work, including cycle times, time to recovery, and lead time",
        "Designing and implementing metrics and queries for project planning",
        "Designing and implementing metrics and queries for development",
        "Designing and implementing metrics and queries for testing",
        "Designing and implementing metrics and queries for security",
        "Designing and implementing metrics and queries for delivery",
        "Designing and implementing metrics and queries for operations",
        "Documenting a project by configuring wikis and process diagrams, including Markdown and Mermaid syntax",
        "Configuring release documentation, including release notes and API documentation",
        "Automating creation of documentation from Git history",
        "Configuring integration using webhooks",
        "Configuring integration between Azure Boards and GitHub repositories",
        "Configuring integration between GitHub or Azure DevOps and Microsoft Teams",
      ],
    },
    {
      title: "Design and Implement a Source Control Strategy",
      weight: 13,
      gate: "Given a branching, repository-scale, or data-recovery requirement, name the specific Git strategy or command that fits.",
      objectives: [
        "Designing a branch strategy -- trunk-based, feature branch, and release branch",
        "Designing and implementing a pull request workflow using branch policies and branch protection rules",
        "Implementing branch merging restrictions using branch policies and branch protection rules",
        "Designing and implementing a strategy for managing large files, including Git Large File Storage (LFS) and git-fat",
        "Designing a strategy for scaling and optimizing a Git repository, including Scalar and cross-repository sharing",
        "Configuring permissions in the source control repository",
        "Configuring tags to organize the source control repository",
        "Recovering specific data using Git commands",
        "Removing specific data from source control",
      ],
    },
    {
      title: "Design and Implement Build and Release Pipelines",
      weight: 53,
      gate: "Given a pipeline, deployment, or infrastructure-as-code requirement, name the specific technique or tool that fits -- not a generic 'automate the deployment'.",
      objectives: [
        "Recommending package management tools, including GitHub Packages and Azure Artifacts",
        "Designing and implementing package feeds and views for local and upstream packages",
        "Designing and implementing a dependency versioning strategy for code assets and packages, including semantic versioning (SemVer) and date-based (CalVer)",
        "Designing and implementing a versioning strategy for pipeline artifacts",
        "Designing and implementing quality and release gates, including security and governance",
        "Designing a comprehensive testing strategy, including local tests, unit tests, integration tests, and load tests",
        "Implementing tests in a pipeline, including configuring test tasks, configuring test agents, and integration of test results",
        "Implementing code coverage analysis",
        "Selecting a deployment automation solution, including GitHub Actions and Azure Pipelines",
        "Designing and implementing a GitHub runner or Azure DevOps agent infrastructure, including cost, tool selection, licenses, connectivity, and maintainability",
        "Designing and implementing integration between GitHub repositories and Azure Pipelines",
        "Developing and implementing pipeline trigger rules",
        "Developing pipelines using YAML",
        "Designing and implementing a strategy for job execution order, including parallelism and multi-stage pipelines",
        "Developing and implementing complex pipeline scenarios, such as hybrid pipelines, VM templates, and self-hosted runners or agents",
        "Creating reusable pipeline elements, including YAML templates, task groups, variables, and variable groups",
        "Designing and implementing checks and approvals using YAML-based environments",
        "Designing a deployment strategy, including blue-green, canary, ring, progressive exposure, feature flags, and A/B testing",
        "Designing a pipeline to ensure that dependency deployments are reliably ordered",
        "Planning for minimizing downtime during deployments using load balancing, rolling deployments, and deployment slot usage and swap",
        "Designing a hotfix path plan for responding to high-priority code fixes",
        "Designing and implementing a resiliency strategy for deployment",
        "Implementing feature flags using Azure App Configuration Feature Manager",
        "Implementing application deployment using containers, binaries, and scripts",
        "Implementing a deployment that includes database tasks",
        "Recommending a configuration management technology for application infrastructure",
        "Implementing a configuration management strategy for application infrastructure",
        "Defining an infrastructure as code (IaC) strategy, including source control and automation of testing and deployment",
        "Designing and implementing desired state configuration for environments, including Azure Automation State Configuration, Azure Resource Manager, Bicep, and Azure Machine Configuration",
        "Designing and implementing Azure Deployment Environments for on-demand self-deployment",
        "Monitoring pipeline health, including failure rate, duration, and flaky tests",
        "Optimizing a pipeline for cost, time, performance, and reliability",
        "Optimizing pipeline concurrency for performance and cost",
        "Designing and implementing a retention strategy for pipeline artifacts and dependencies",
        "Migrating a pipeline from classic to YAML in Azure Pipelines",
      ],
    },
    {
      title: "Develop a Security and Compliance Plan",
      weight: 13,
      gate: "Given a DevOps identity, secrets, or scanning requirement, name the specific control that fits, not just 'secure the pipeline'.",
      objectives: [
        "Choosing between Microsoft Entra service principals and managed identities for Azure resources, system-assigned and user-assigned",
        "Implementing and managing GitHub authentication, including GitHub Apps, GITHUB_TOKEN, and personal access tokens",
        "Implementing and managing Azure DevOps service connections and personal access tokens",
        "Designing and implementing permissions and roles in GitHub",
        "Designing and implementing permissions and security groups in Azure DevOps",
        "Recommending appropriate access levels, including stakeholder access in Azure DevOps and outside collaborator access in GitHub",
        "Configuring projects and teams in Azure DevOps",
        "Implementing and managing secrets, keys, and certificates using Azure Key Vault",
        "Implementing and managing secrets and secretless authentication -- for example, workload identity federation/OpenID Connect -- in GitHub Actions and Azure Pipelines",
        "Designing and implementing a strategy for managing sensitive files during deployment, including Azure Pipelines secure files",
        "Designing pipelines to prevent leakage of sensitive information",
        "Designing a strategy for security and compliance scanning, including dependency, code, secret, and licensing scanning",
        "Configuring Microsoft Defender for Cloud DevOps Security",
        "Configuring GitHub Advanced Security for GitHub and GitHub Advanced Security for Azure DevOps",
        "Integrating GitHub Advanced Security with Microsoft Defender for Cloud",
        "Automating container scanning, including scanning container images and configuring an action to run CodeQL analysis in a container",
        "Automating analysis of vulnerabilities of open-source components using Dependabot alerts",
      ],
    },
    {
      title: "Implement an Instrumentation Strategy",
      weight: 8,
      gate: "Given a DevOps monitoring or telemetry-analysis requirement, name the specific Azure Monitor or GitHub instrumentation control that fits.",
      objectives: [
        "Configuring Azure Monitor and Azure Monitor Logs to integrate with DevOps tools",
        "Configuring collection of telemetry using Azure Monitor Application Insights, Azure VM Insights, Azure Container Insights, Azure Monitor for Storage, and Azure Monitor for Networks",
        "Configuring monitoring in GitHub, including enabling insights and creating and configuring charts",
        "Configuring alerts for events in GitHub Actions and Azure Pipelines",
        "Inspecting infrastructure performance indicators, including CPU, memory, disk, and network",
        "Analyzing metrics using collected telemetry, including usage and application performance",
        "Inspecting distributed tracing using Azure Monitor Application Insights",
        "Interrogating logs using basic Kusto Query Language (KQL) queries",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Specialty: Microsoft Certified: Azure for SAP Workloads Specialty (AZ-120)
// 100 minutes, minimum passing score 700. Microsoft strongly recommends the
// Azure Administrator Associate certification first.
// Domains: Migrate SAP workloads to Azure 25-30% / Design and implement
// infrastructure to support SAP workloads 25-30% / High availability and
// disaster recovery 20-25% / Maintain SAP workloads on Azure 20-25%.

export const AZURE_AZ120_TRACK: SeedTrack = {
  code: "AZ120",
  title: "Azure for SAP Workloads Specialty Coach",
  description:
    "Microsoft Certified: Azure for SAP Workloads Specialty (AZ-120): planning, migrating, and administering SAP landscapes on Azure -- migration strategy and SAP RISE integration, compute/networking/storage infrastructure for SAP virtual machines, high availability and disaster recovery (clustering, Pacemaker, Site Recovery), and ongoing performance optimization and monitoring.",
  trackType: "certification",
  subcategorySlug: "it-certifications",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-for-sap-workloads-specialty/",
  sourceVerifiedAt: VERIFIED_AT,
  credential: {
    ...AZURE_PROVIDER,
    credentialSlug: "azure-for-sap-workloads-specialty",
    credentialName: "Microsoft Certified: Azure for SAP Workloads Specialty",
    credentialUrl: "https://learn.microsoft.com/en-us/credentials/certifications/azure-for-sap-workloads-specialty/",
    examCode: "AZ-120",
    status: "active",
    officialObjectivesUrl: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-120",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "Experience as an architect or engineer designing and managing SAP landscapes on Azure, including RISE with SAP, with extensive knowledge of SAP HANA, SAP Business Suite, and SAP NetWeaver, plus virtualization, cloud infrastructure, storage, high availability, disaster recovery, and networking; an Azure Administrator Associate certification is strongly recommended first.",
    durationMinutes: 100,
    questionFormat: "Microsoft does not publish an exact question count for AZ-120",
    passingScorePolicy: "Minimum passing score 700",
  },
  units: [
    {
      title: "Migrate SAP Workloads to Azure",
      weight: 28,
      gate: "Given an SAP migration-planning requirement, name the specific target-infrastructure decision or RISE integration point that fits, not just 'move it to Azure'.",
      objectives: [
        "Estimating target sizing for SAP workloads",
        "Identifying supported scenarios for SAP deployments on Azure",
        "Identifying compute, storage, and network requirements for SAP workloads",
        "Assessing constraints imposed by subscription models and quota limits",
        "Identifying software licensing requirements for target workloads",
        "Identifying cost implications for target workloads",
        "Specifying an Azure support plan for the target infrastructure",
        "Choosing between lift and shift, lift-shift-migrate, and lift-shift-migrate to HANA",
        "Choosing an appropriate SAP workload migration strategy and tools",
        "Designing and implementing authorization and access control for SAP workloads",
        "Designing and implementing governance and compliance using Azure Policy",
        "Designing and implementing authentication for SAP workloads",
        "Designing and implementing authentication for SAP software as a service (SaaS) applications",
        "Designing and implementing a management hierarchy, including management groups, subscriptions, and resource groups",
        "Designing Azure landing zones for SAP",
        "Designing networking for SAP RISE",
        "Implementing networking for SAP RISE",
        "Designing and implementing Azure compute, network, and storage services with SAP RISE",
        "Designing and implementing integration of data management services, such as data archiving",
        "Designing and implementing integration of identity and security services with SAP RISE",
      ],
    },
    {
      title: "Design and Implement Infrastructure to Support SAP Workloads on Azure",
      weight: 25,
      gate: "Given a compute, networking, or storage requirement for SAP virtual machines, name the specific Azure control that fits.",
      objectives: [
        "Choosing an SAP-certified Azure virtual machine for a given SAP workload",
        "Configuring the Azure VM extension for SAP solutions",
        "Deploying an operating system using an Azure Marketplace image",
        "Creating a custom image and deploying it to an Azure virtual machine",
        "Automating a deployment of Azure virtual machines using infrastructure as code, including Bicep and Azure Resource Manager (ARM) templates",
        "Automating a deployment using the SAP Deployment Automation Framework",
        "Automating a deployment using Azure Center for SAP solutions",
        "Designing and implementing virtual networks and subnets",
        "Implementing Accelerated Networking for Azure virtual machines",
        "Designing and configuring proximity placement groups",
        "Designing networking to meet SAP workload latency requirements",
        "Designing and implementing network flow control",
        "Designing and implementing network security",
        "Designing and implementing service endpoints and private endpoints for Azure Storage",
        "Designing name resolution for integration with Azure DNS",
        "Designing and configuring ExpressRoute for hybrid connectivity",
        "Choosing a storage type",
        "Specifying when to use disk striping and simple volumes",
        "Designing for storage security considerations",
        "Designing and implementing data protection",
        "Designing and implementing caching for disks",
        "Configuring Write Accelerator",
        "Configuring encryption for storage, disks, and data",
        "Designing and implementing volumes using Azure NetApp Files",
        "Designing and implementing volumes using Azure Files",
      ],
    },
    {
      title: "Design and Implement High Availability and Disaster Recovery",
      weight: 23,
      gate: "Given an SAP resiliency requirement, name the specific clustering, replication, or Site Recovery configuration that fits, not just 'make it available'.",
      objectives: [
        "Designing for service-level agreement (SLA) considerations",
        "Designing and deploying SAP workloads into availability sets and availability zones",
        "Designing and implementing load balancing for high availability",
        "Configuring clustering for HANA and SAP Central Services (SCS)",
        "Configuring clustering for SQL",
        "Configuring Pacemaker and STONITH",
        "Configuring an Azure fence agent or STONITH Block Device (SBD)",
        "Designing and configuring storage-level replication for SAP workloads",
        "Configuring restart of SAP systems, instances, and HANA databases",
        "Designing and implementing an Azure Site Recovery strategy for an SAP infrastructure",
        "Designing a disaster recovery solution with regional considerations",
        "Specifying network configurations for disaster recovery",
        "Designing a backup strategy to meet SLA requirements",
        "Implementing policies for backups and snapshots",
        "Configuring and validating snapshots and backups for SAP workloads",
        "Performing backup and restore",
        "Testing disaster recovery",
      ],
    },
    {
      title: "Maintain SAP Workloads on Azure",
      weight: 23,
      gate: "Given an ongoing SAP cost or monitoring requirement, name the specific Azure Advisor, Monitor, or Center for SAP solutions control that fits.",
      objectives: [
        "Optimizing performance and costs for an SAP workload using Azure Advisor recommendations",
        "Analyzing and optimizing network performance",
        "Optimizing costs using Azure Savings Plans or Reserved Instances for SAP virtual machines",
        "Optimizing performance and costs by resizing Azure virtual machines",
        "Optimizing storage costs",
        "Optimizing data performance using archiving",
        "Optimizing performance and costs of SAP application servers and databases",
        "Monitoring Azure virtual machines using Azure Monitor",
        "Monitoring high availability using Azure Monitor",
        "Monitoring storage using Azure Monitor",
        "Monitoring networking using Azure Monitor and Azure Network Watcher",
        "Configuring Azure Monitor for SAP solutions",
        "Managing backups using Azure Backup",
        "Starting and stopping SAP systems using Azure Center for SAP solutions",
        "Managing virtual instances using Azure Center for SAP solutions",
        "Implementing the SAP Landscape Management (LaMa) connector for Azure",
      ],
    },
  ],
};

export const AZURE_TRACKS: SeedTrack[] = [
  AZURE_AZ900_TRACK,
  AZURE_AZ104_TRACK,
  AZURE_AZ305_TRACK,
  AZURE_AI901_TRACK,
  AZURE_DP900_TRACK,
  AZURE_AZ700_TRACK,
  AZURE_AZ140_TRACK,
  AZURE_DP300_TRACK,
  AZURE_AZ400_TRACK,
  AZURE_AZ120_TRACK,
];
