// Nursing tracks: the licensure ladder and the NCLEX examinations.
//
// Every category name, percentage and content area below was read on
// 2026-09-18 from the source each track cites -- for the NCLEX tracks, the
// NCSBN test plan PDF itself, not a summary of it. Two things that older
// notes and general training data get wrong, corrected here:
//
//   - The 2026 RN plan renames the subcategory "Safety and Infection
//     Control" to "Safety and Infection Prevention and Control".
//   - The published percentages are ranges (Management of Care is 15-21%),
//     but NCSBN also prints exact planning midpoints in the distribution
//     chart. Those midpoints are what `weight` carries, because they sum to
//     100; the published range is kept in `rangeLabel` so the learner sees
//     what the vendor actually promises.
//
// Objectives are written in our own words from the test plan's content
// areas. They are deliberately not copied: NCSBN grants reproduction to
// boards of nursing and nonprofit education programs only, and prohibits
// commercial use, so the structure (which is fact) is followed while the
// phrasing is ours.
//
// Every track here sets requiresAcknowledgement. Nursing content acted on in
// practice has patient-safety consequences, so migration 012's gate applies:
// the learner accepts a course-specific disclaimer, recorded against their
// account, before any lesson is taught.

import type { SeedTrack } from "../data";

const NCSBN_PROVIDER = {
  providerSlug: "ncsbn",
  providerName: "National Council of State Boards of Nursing",
  providerUrl: "https://www.ncsbn.org/",
  subcategorySlug: "nclex-preparation",
  credentialType: "licensure_examination",
} as const;

const VERIFIED_AT = "2026-09-18T00:00:00Z";

// The disclaimer every nursing track points at. The wording lives in the app
// (mobile/src/content/disclaimers.ts) so it can be corrected without a data
// migration across every track that shares it.
const NURSING_DISCLAIMER_KEY = "nursing-clinical-content";

// ---------------------------------------------------------------------------
// NCLEX-RN (2026 Test Plan, effective April 1 2026 through March 31 2029)
// Computerized adaptive, variable length. Clinical judgment is measured by
// 18 case study items (three item sets) plus roughly 10% stand-alone items.
// Client Needs midpoints: 18 / 13 / 9 / 9 / 9 / 16 / 12 / 14.
// ---------------------------------------------------------------------------
export const NCLEX_RN_TRACK: SeedTrack = {
  code: "NCLEXRN",
  title: "NCLEX-RN Coach",
  description:
    "The registered nurse licensure examination, built on the 2026 NCSBN test plan: the four Client Needs categories and their eight subcategories, weighted as the exam weights them, with clinical judgment treated as the thing being tested rather than a topic to revise.",
  trackType: "certification",
  subcategorySlug: "nclex-preparation",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://www.ncsbn.org/public-files/2026_RN_Test%20Plan_English-F.pdf",
  sourceVerifiedAt: VERIFIED_AT,
  requiresAcknowledgement: true,
  disclaimerKey: NURSING_DISCLAIMER_KEY,
  disclaimerVersion: 1,
  credential: {
    ...NCSBN_PROVIDER,
    credentialSlug: "nclex-rn",
    credentialName: "NCLEX-RN Examination",
    credentialUrl: "https://www.ncsbn.org/exams/testplans.page",
    basis: "regulatory_licensure",
    examCode: "NCLEX-RN",
    examRevision: "2026 Test Plan",
    standardName: "NCLEX-RN Test Plan",
    standardRevision: "2026",
    status: "active",
    effectiveDate: "2026-04-01",
    retirementDate: "2029-03-31",
    officialObjectivesUrl:
      "https://www.ncsbn.org/public-files/2026_RN_Test%20Plan_English-F.pdf",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "Completion of a state-approved registered nursing program. The plan assumes entry-level practice: the candidate is being measured against what a newly licensed RN must do safely, not against experienced practice.",
    questionFormat:
      "Computerized adaptive, variable length; includes 18 clinical judgment case study items (three item sets) and approximately 10% stand-alone clinical judgment items; item types include multiple choice, multiple response, and other formats",
    passingScorePolicy:
      "Pass/fail against a standard set by NCSBN rather than a percentage score; decided by the 95% confidence interval rule, the maximum-length rule, or the run-out-of-time rule",
  },
  units: [
    {
      title: "Management of Care",
      rangeLabel: "15-21% of the exam",
      weight: 18,
      gate: "Given a shift of assigned clients, decide who is seen first and what goes to whom -- and defend the delegation against scope of practice, not against convenience.",
      objectives: [
        "Prioritising by acuity rather than by who asked first",
        "Airway, breathing, circulation as a prioritisation frame, and where it stops helping",
        "Unstable versus stable: recognising which client is actually deteriorating",
        "Assignment and delegation are different acts with different accountability",
        "Matching a task to the competency of an LPN/VN, assistive personnel, or another RN",
        "The five rights of delegation: task, circumstance, person, direction, supervision",
        "What can never be delegated: assessment, evaluation, teaching, unstable clients",
        "Supervising delegated care and evaluating the outcome rather than assuming it",
        "Giving and receiving handoff of care on assigned clients",
        "Safe admission, transfer and discharge procedures",
        "Continuity of care across settings and shifts",
        "Advance directives: living will, health care proxy, durable power of attorney for health care",
        "Integrating an advance directive into the plan of care rather than filing it",
        "Assessing what the client actually understands about self-determination",
        "Acting as client advocate when the client's decision is not the family's preference",
        "Choosing the right advocacy resource: social work, chain of command, interpreter",
        "Supporting unbiased treatment and equal access to care across culture, ethnicity, sexual orientation and gender identity",
        "Client rights, and the nurse's duty to educate clients and staff about them",
        "Informed consent: the nurse verifies it, the provider obtains it",
        "Confirming the client received education and consented before a procedure",
        "Confidentiality and information security, including disclosure through social media",
        "Receiving, verifying and implementing provider orders",
        "Documenting with approved terminology, accurately and in time to be useful",
        "Accessing client records within facility regulation",
        "Legal issues that reach the nurse: refusal of treatment, client valuables, interpreter services",
        "Mandatory reporting: abuse, neglect, communicable disease",
        "Recognising ethical dilemmas and reporting them",
        "Practising within the nurses' code of ethics and the legal scope of practice",
        "Recognising the limits of one's own competence and using resources",
        "Collaborating with the multidisciplinary team: physical therapy, nutrition, social work",
        "Case management for a client with chronic or complex needs",
        "Assessing the need for a referral and obtaining the order it requires",
        "Community resources: respite care, social services, shelters",
        "Performance and quality improvement: what the activity is and how the nurse participates",
        "Evaluating what a quality improvement measure actually changed",
        "Managing conflict among clients and staff",
        "Organising a workload so time is spent where acuity is",
      ],
    },
    {
      title: "Safety and Infection Prevention and Control",
      rangeLabel: "10-16% of the exam",
      weight: 13,
      gate: "Given a client, a room and a diagnosis, name the precautions required and the hazards present -- and act on the error you would rather not report.",
      objectives: [
        "Principles of infection prevention: hand hygiene, aseptic technique, isolation, sterile technique",
        "Standard precautions as the floor that applies to every client",
        "Transmission-based precautions matched to the mode: airborne, droplet, contact",
        "Enhanced barrier precautions and when they apply",
        "Setting up and maintaining a sterile field",
        "Evaluating whether aseptic technique was actually performed correctly",
        "Protecting the immunocompromised client",
        "Communicable disease: modes of transmission and correct reporting procedure",
        "Educating client and staff on infection prevention measures",
        "Correct client identification before any care is given",
        "Assessing the client for allergies and acting on what is found",
        "Factors that raise accident and injury risk: age, developmental stage, mental status, lifestyle",
        "Deficits that impede safety: visual, hearing, sensory and perceptual",
        "Seizure precautions for the at-risk client",
        "Room assignment decisions for the cognitively impaired client",
        "Verifying that a treatment order is appropriate as well as accurate",
        "Home safety assessment: lighting, handrails, kitchen and fire hazards",
        "Infant and child car seat use",
        "Ergonomic principles and body mechanics when providing care",
        "Assessing balance and transfer ability before planning mobility care",
        "Safe use of equipment, and removing malfunctioning equipment from the care area",
        "Handling biohazardous, flammable and infectious materials",
        "Safe implementation of internal radiation therapy",
        "Restraints and safety devices: assessing appropriateness of the type used",
        "Following the legal and facility requirements that attach to restraint use",
        "Monitoring and evaluating the client's response to a restraint",
        "Acknowledging and documenting practice errors and near misses",
        "Incident, event and variance reporting, and evaluating the response to it",
        "Reporting, intervening in or escalating unsafe staff practice",
        "Emergency response: nursing roles in disaster planning and drills",
        "Deciding which clients can be discharged in a disaster situation",
        "Security plans: newborn security, controlled access, violence, environmental",
        "Triage and evacuation principles",
      ],
    },
    {
      title: "Health Promotion and Maintenance",
      rangeLabel: "6-12% of the exam",
      weight: 9,
      gate: "Given a client at any age, say what is expected for that stage, what screening is due, and what the teaching should target.",
      objectives: [
        "Expected age-related change, and the client's reaction to it",
        "Care and education from birth through 2 years",
        "Care and education for ages 3 through 17",
        "Care and education for the adult client aged 18 to 64",
        "Care and education for the adult client aged 65 and over",
        "Developmental stages and the transitions between them",
        "Prenatal care and education",
        "Assessing psychosocial response to pregnancy: support, perception, coping",
        "Calculating the expected delivery date",
        "Fetal heart rate at routine prenatal examinations",
        "Care of the antepartum client and the client in labor",
        "Postpartum care, and assessing for hemorrhage and infection",
        "Newborn care and education",
        "Comprehensive health assessment versus targeted screening",
        "Targeted screening: vision, nutrition, depression",
        "Health history and risk assessment, including family and genetic history",
        "Interviewing technique when taking a health history",
        "Choosing physical assessment equipment and technique appropriate to the client",
        "Disease prevention and health maintenance recommendations",
        "Community health education and participation in it",
        "High-risk behaviours: identifying them and teaching prevention and treatment",
        "Lifestyle choices, including sexuality, contraception and family planning",
        "Contraindications to a chosen contraceptive method",
        "Recognising the socially or environmentally isolated client",
        "Alternative and homeopathic practices the client is already using",
        "Assessing readiness to learn, learning preference, and barriers to learning",
        "Minimising communication barriers so teaching actually lands",
        "Self-care capacity in the home environment, and planning care around it",
        "Evaluating whether the client understood the health promotion behaviour taught",
      ],
    },
    {
      title: "Psychosocial Integrity",
      rangeLabel: "6-12% of the exam",
      weight: 9,
      gate: "Given a client in distress, choose the response that opens the conversation rather than closing it -- and recognise when distress has become a safety problem.",
      objectives: [
        "Therapeutic communication technique, and what makes a response non-therapeutic",
        "Encouraging the client to put feelings into words",
        "Allowing silence and time rather than filling it",
        "Assessing verbal and nonverbal communication needs",
        "Recognising nonverbal cues to physical and psychological stress",
        "Evaluating whether communication with the client was effective",
        "Assessing for abuse or neglect, and reporting or escalating it",
        "Risk factors for domestic, child, elder and sexual abuse",
        "Providing a safe environment for the abused or neglected client",
        "Assessing the potential for violence and using safety precautions",
        "Identifying the client in crisis and applying crisis intervention technique",
        "Coping mechanisms, and evaluating constructive use of defence mechanisms",
        "Adapting to temporary and permanent role change",
        "Supporting the client with an unexpected altered body image",
        "Substance use disorder: assessing for misuse, dependency and withdrawal",
        "Managing withdrawal and toxicity symptoms",
        "Non-substance dependencies such as gambling",
        "Signs and symptoms of acute and chronic mental illness",
        "Impaired cognition: memory loss, poor hygiene, altered judgment",
        "Alterations in mood, judgment, cognition and reasoning",
        "Behavioural intervention and helping the client regain self-control",
        "Orienting the client to reality, and providing reality-based diversion",
        "Sensory and perceptual alterations, and strategies for the client experiencing them",
        "Grief and loss, including anticipatory grieving",
        "Expected reactions to grief, and resources for bereavement",
        "End-of-life needs: fear, loss of control, financial concern, role change",
        "Psychosocial support for the family and caregiver at end of life",
        "Cultural practice and belief incorporated into the plan of care",
        "Religious and spiritual influences, including conflict between belief and treatment",
        "Family dynamics, stressors and barriers to family functioning",
        "Support systems, and involving the client in decisions about care",
        "Stress management technique, and evaluating the client's use of it",
        "Promoting and maintaining a therapeutic environment",
      ],
    },
    {
      title: "Basic Care and Comfort",
      rangeLabel: "6-12% of the exam",
      weight: 9,
      gate: "Given a client who cannot fully care for themselves, provide the assistance the deficit actually calls for while keeping dignity intact.",
      objectives: [
        "Assessing performance of activities of daily living and assisting where needed",
        "Maintaining dignity and privacy during personal care",
        "Personal hygiene for the dependent client",
        "Assistive devices: prosthetic limbs, hearing aids, eating utensils",
        "Compensating for a physical or sensory impairment",
        "Applying, maintaining and removing orthopedic devices",
        "Mobility and immobility, and the complications immobility causes",
        "Measures that promote circulation: range of motion, positioning, mobilisation",
        "Skin assessment and maintaining skin and tissue integrity",
        "Nutrition and oral hydration, and evaluating nutritional status",
        "Providing nutrition through tube feedings",
        "Evaluating intake and output and acting on the imbalance",
        "Bowel and bladder elimination, and managing an alteration in either",
        "Performing irrigations of bladder, ear or eye",
        "Rest and sleep: assessing the pattern and intervening on it",
        "Assessing for pain and acting on the assessment",
        "Nonpharmacological comfort measures",
        "Complementary therapies: potential benefit and contraindication",
        "Postmortem care",
      ],
    },
    {
      title: "Pharmacological and Parenteral Therapies",
      rangeLabel: "13-19% of the exam",
      weight: 16,
      gate: "Given an order, a client and a calculation, give the medication safely -- or refuse to, for a reason you can name.",
      objectives: [
        "The rights of medication administration, applied rather than recited",
        "Reviewing contraindications, allergies, lab results and interactions before giving",
        "Evaluating whether the medication order is appropriate and accurate for this client",
        "Performing the calculations medication administration requires",
        "Administering and documenting medications by common routes",
        "Administering and documenting medications by parenteral routes",
        "Mixing medications from two vials",
        "Titrating a dose against assessment and ordered parameters",
        "High-risk medications and the extra handling they require",
        "Controlled substances within regulatory guidelines",
        "Safe storage and safe disposal of medication",
        "Medication reconciliation and the nurse's part in it",
        "Expected actions and outcomes of a prescribed medication",
        "Evaluating the client's response to a medication over time",
        "Adverse effects, side effects, contraindications and interactions distinguished",
        "Recognising an allergic reaction to a medication",
        "Incompatibilities among a client's prescribed medications",
        "Notifying the provider, and documenting what was observed and done",
        "Teaching the client which effects warrant a call to the provider",
        "Pharmacological pain management, including p.r.n. decision-making",
        "Pain medication appropriate to age and diagnosis, including pregnancy and older adults",
        "Evaluating and documenting response to pain medication",
        "Peripheral intravenous therapy: vein selection and site maintenance",
        "Preparing the client for venous access device insertion",
        "Monitoring an infusion pump, including patient-controlled analgesia",
        "Central venous access devices: access, maintenance and client teaching",
        "Blood and blood products: identification, consent and crossmatch verification",
        "Venous access adequate for blood product administration",
        "Administering blood products and evaluating the response",
        "Total parenteral nutrition: administration and client teaching",
        "TPN complications: hyperglycemia, fluid imbalance, infection",
      ],
    },
    {
      title: "Reduction of Risk Potential",
      rangeLabel: "9-15% of the exam",
      weight: 12,
      gate: "Given a client before or after a procedure, name the complication most likely to develop and the finding that would announce it.",
      objectives: [
        "Assessing and responding to changes and trends in vital signs",
        "Applying pathophysiology when measuring and interpreting vital signs",
        "Comparing client laboratory values against normal values",
        "Monitoring laboratory values and notifying the provider about results",
        "Obtaining blood specimens, and specimens other than blood",
        "Teaching the client the purpose and procedure of an ordered test",
        "Caring for the client undergoing diagnostic testing",
        "Comparing diagnostic findings against pretest results",
        "Testing within the nurse's scope: ECG, point-of-care testing, fetal monitoring",
        "Monitoring maternal and fetal diagnostic tests",
        "Potential for aspiration: feeding tube, sedation, swallowing difficulty",
        "Potential for skin breakdown: immobility, nutrition, incontinence",
        "Risk of insufficient vascular perfusion",
        "Comparing current data against the client's own baseline",
        "Monitoring output for change from baseline",
        "Focused and system-specific assessment",
        "Abnormal peripheral pulses after a procedure",
        "Abnormal neurologic status: consciousness, muscle strength, mobility",
        "Peripheral edema, and signs of hypo- or hyperglycemia",
        "Factors that delay wound healing",
        "Risk assessment for falls, sensory impairment, mobility and skin integrity",
        "Recognising a trend in the client's condition and intervening on it",
        "Abnormal response following a diagnostic test or procedure",
        "Monitoring for signs of bleeding",
        "Positioning to prevent complications after a procedure",
        "Inserting, maintaining and removing a nasogastric or oral gastrointestinal tube",
        "Inserting, maintaining and removing a urinary catheter",
        "Inserting, maintaining and removing a peripheral intravenous line",
        "Maintaining tube patency, including chest tubes and decompression tubes",
        "Maintaining a percutaneous feeding tube",
        "Devices that promote venous return: antiembolism stockings, compression devices",
        "Intervening on circulatory complications: hemorrhage, embolus, shock",
        "Preventing aspiration, including verifying tube placement",
        "Preventing neurologic complications such as footdrop and numbness",
        "Recovery from local, regional and general anesthesia",
        "Preoperative care, and preoperative and postoperative teaching",
        "Managing the client before, during and after moderate sedation",
        "Monitoring therapeutic devices: chest tube, drains, continuous bladder irrigation",
        "Moving a client with a musculoskeletal condition without further injury",
        "Evaluating the client's response to a procedure or treatment",
      ],
    },
    {
      title: "Physiological Adaptation",
      rangeLabel: "11-17% of the exam",
      weight: 14,
      gate: "Given a client whose condition is changing, connect the pathophysiology to the finding in front of you and act at the right moment.",
      objectives: [
        "General principles of pathophysiology: injury and repair, immunity, cellular structure",
        "Identifying the pathophysiology behind an acute or chronic condition",
        "Assessing the client's adaptation to illness or health alteration",
        "Fluid and electrolyte imbalance: recognising the signs and symptoms",
        "Managing the client with a fluid or electrolyte imbalance",
        "Evaluating the response to correction of an imbalance",
        "Decreased cardiac output: diminished pulses, hypotension",
        "Cardiac rhythm strip abnormalities and what they signify",
        "Hemodynamic values and intervening on abnormal ones",
        "Managing care of the client on telemetry or with a pacing device",
        "Monitoring and maintaining arterial lines",
        "Hemodialysis, continuous renal replacement therapy and peritoneal dialysis",
        "Managing the client with impaired ventilation or oxygenation",
        "Monitoring and caring for the client on a ventilator",
        "Performing suctioning, and providing pulmonary hygiene",
        "Wound care, dressing change, and monitoring wounds for infection",
        "Managing drainage devices, including negative pressure wound therapy",
        "Ostomy care and client education",
        "Removing sutures or staples",
        "Postoperative care and evaluating the response to surgery",
        "Caring for the client with increased intracranial pressure",
        "Internal monitoring devices: intracranial pressure, intrauterine pressure",
        "Care of the client who has had a seizure",
        "Infectious disease: signs, symptoms and incubation periods",
        "Evaluating response to treatment for an infectious disease",
        "Adverse effects of radiation therapy and interventions for them",
        "Implementing and monitoring phototherapy",
        "Maintaining the client's optimal temperature",
        "Complications of pregnancy, labor and delivery: eclampsia, hemorrhage, precipitous labor",
        "Signs of potential prenatal complications",
        "Assisting with invasive procedures: central line, thoracentesis, bronchoscopy",
        "Medical emergencies: applying pathophysiology under time pressure",
        "Emergency care procedures, including wound dehiscence",
        "Identifying client data that must be reported immediately",
        "Notifying the provider about an unexpected response or emergency",
        "Unexpected adverse response to therapy, and recognising complications early",
        "Evaluating achievement of the client's treatment goals",
      ],
    },
  ],
};

export const NURSING_TRACKS: SeedTrack[] = [NCLEX_RN_TRACK];
