// Nursing tracks: the licensure ladder and the NCLEX examinations.
//
// Every category name, percentage and content area below was read on
// 2026-09-18 from the source each track cites -- for the NCLEX tracks, the
// NCSBN test plan PDF itself, not a summary of it. Two things that older
// notes and general training data get wrong, corrected here:
//
//   - The 2026 RN plan renames the subcategory "Safety and Infection
//     Control" to "Safety and Infection Prevention and Control".
//   - The published percentages are ranges (Management of Care is 15-21%),
//     but NCSBN also prints exact planning midpoints in the distribution
//     chart. Those midpoints are what `weight` carries, because they sum to
//     100; the published range is kept in `rangeLabel` so the learner sees
//     what the vendor actually promises.
//
// Objectives are written in our own words from the test plan's content
// areas. They are deliberately not copied: NCSBN grants reproduction to
// boards of nursing and nonprofit education programs only, and prohibits
// commercial use, so the structure (which is fact) is followed while the
// phrasing is ours.
//
// Every track here sets requiresAcknowledgement. Nursing content acted on in
// practice has patient-safety consequences, so migration 012's gate applies:
// the learner accepts a course-specific disclaimer, recorded against their
// account, before any lesson is taught.

import type { SeedTrack } from "../data";

const NCSBN_PROVIDER = {
  providerSlug: "ncsbn",
  providerName: "National Council of State Boards of Nursing",
  providerUrl: "https://www.ncsbn.org/",
  subcategorySlug: "nclex-preparation",
  credentialType: "licensure_examination",
} as const;

const VERIFIED_AT = "2026-09-18T00:00:00Z";

// The disclaimer every nursing track points at. The wording lives in the app
// (mobile/src/content/disclaimers.ts) so it can be corrected without a data
// migration across every track that shares it.
const NURSING_DISCLAIMER_KEY = "nursing-clinical-content";

// ---------------------------------------------------------------------------
// NCLEX-RN (2026 Test Plan, effective April 1 2026 through March 31 2029)
// Computerized adaptive, variable length. Clinical judgment is measured by
// 18 case study items (three item sets) plus roughly 10% stand-alone items.
// Client Needs midpoints: 18 / 13 / 9 / 9 / 9 / 16 / 12 / 14.
// ---------------------------------------------------------------------------
export const NCLEX_RN_TRACK: SeedTrack = {
  code: "NCLEXRN",
  title: "NCLEX-RN Coach",
  description:
    "The registered nurse licensure examination, built on the 2026 NCSBN test plan: the four Client Needs categories and their eight subcategories, weighted as the exam weights them, with clinical judgment treated as the thing being tested rather than a topic to revise.",
  trackType: "certification",
  subcategorySlug: "nclex-preparation",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://www.ncsbn.org/public-files/2026_RN_Test%20Plan_English-F.pdf",
  sourceVerifiedAt: VERIFIED_AT,
  requiresAcknowledgement: true,
  disclaimerKey: NURSING_DISCLAIMER_KEY,
  disclaimerVersion: 1,
  credential: {
    ...NCSBN_PROVIDER,
    credentialSlug: "nclex-rn",
    credentialName: "NCLEX-RN Examination",
    credentialUrl: "https://www.ncsbn.org/exams/testplans.page",
    basis: "regulatory_licensure",
    examCode: "NCLEX-RN",
    examRevision: "2026 Test Plan",
    standardName: "NCLEX-RN Test Plan",
    standardRevision: "2026",
    status: "active",
    effectiveDate: "2026-04-01",
    retirementDate: "2029-03-31",
    officialObjectivesUrl:
      "https://www.ncsbn.org/public-files/2026_RN_Test%20Plan_English-F.pdf",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "Completion of a state-approved registered nursing program. The plan assumes entry-level practice: the candidate is being measured against what a newly licensed RN must do safely, not against experienced practice.",
    questionFormat:
      "Computerized adaptive, variable length; includes 18 clinical judgment case study items (three item sets) and approximately 10% stand-alone clinical judgment items; item types include multiple choice, multiple response, and other formats",
    passingScorePolicy:
      "Pass/fail against a standard set by NCSBN rather than a percentage score; decided by the 95% confidence interval rule, the maximum-length rule, or the run-out-of-time rule",
  },
  units: [
    {
      title: "Management of Care",
      rangeLabel: "15-21% of the exam",
      weight: 18,
      gate: "Given a shift of assigned clients, decide who is seen first and what goes to whom -- and defend the delegation against scope of practice, not against convenience.",
      objectives: [
        "Prioritising by acuity rather than by who asked first",
        "Airway, breathing, circulation as a prioritisation frame, and where it stops helping",
        "Unstable versus stable: recognising which client is actually deteriorating",
        "Assignment and delegation are different acts with different accountability",
        "Matching a task to the competency of an LPN/VN, assistive personnel, or another RN",
        "The five rights of delegation: task, circumstance, person, direction, supervision",
        "What can never be delegated: assessment, evaluation, teaching, unstable clients",
        "Supervising delegated care and evaluating the outcome rather than assuming it",
        "Giving and receiving handoff of care on assigned clients",
        "Safe admission, transfer and discharge procedures",
        "Continuity of care across settings and shifts",
        "Advance directives: living will, health care proxy, durable power of attorney for health care",
        "Integrating an advance directive into the plan of care rather than filing it",
        "Assessing what the client actually understands about self-determination",
        "Acting as client advocate when the client's decision is not the family's preference",
        "Choosing the right advocacy resource: social work, chain of command, interpreter",
        "Supporting unbiased treatment and equal access to care across culture, ethnicity, sexual orientation and gender identity",
        "Client rights, and the nurse's duty to educate clients and staff about them",
        "Informed consent: the nurse verifies it, the provider obtains it",
        "Confirming the client received education and consented before a procedure",
        "Confidentiality and information security, including disclosure through social media",
        "Receiving, verifying and implementing provider orders",
        "Documenting with approved terminology, accurately and in time to be useful",
        "Accessing client records within facility regulation",
        "Legal issues that reach the nurse: refusal of treatment, client valuables, interpreter services",
        "Mandatory reporting: abuse, neglect, communicable disease",
        "Recognising ethical dilemmas and reporting them",
        "Practising within the nurses' code of ethics and the legal scope of practice",
        "Recognising the limits of one's own competence and using resources",
        "Collaborating with the multidisciplinary team: physical therapy, nutrition, social work",
        "Case management for a client with chronic or complex needs",
        "Assessing the need for a referral and obtaining the order it requires",
        "Community resources: respite care, social services, shelters",
        "Performance and quality improvement: what the activity is and how the nurse participates",
        "Evaluating what a quality improvement measure actually changed",
        "Managing conflict among clients and staff",
        "Organising a workload so time is spent where acuity is",
      ],
    },
    {
      title: "Safety and Infection Prevention and Control",
      rangeLabel: "10-16% of the exam",
      weight: 13,
      gate: "Given a client, a room and a diagnosis, name the precautions required and the hazards present -- and act on the error you would rather not report.",
      objectives: [
        "Principles of infection prevention: hand hygiene, aseptic technique, isolation, sterile technique",
        "Standard precautions as the floor that applies to every client",
        "Transmission-based precautions matched to the mode: airborne, droplet, contact",
        "Enhanced barrier precautions and when they apply",
        "Setting up and maintaining a sterile field",
        "Evaluating whether aseptic technique was actually performed correctly",
        "Protecting the immunocompromised client",
        "Communicable disease: modes of transmission and correct reporting procedure",
        "Educating client and staff on infection prevention measures",
        "Correct client identification before any care is given",
        "Assessing the client for allergies and acting on what is found",
        "Factors that raise accident and injury risk: age, developmental stage, mental status, lifestyle",
        "Deficits that impede safety: visual, hearing, sensory and perceptual",
        "Seizure precautions for the at-risk client",
        "Room assignment decisions for the cognitively impaired client",
        "Verifying that a treatment order is appropriate as well as accurate",
        "Home safety assessment: lighting, handrails, kitchen and fire hazards",
        "Infant and child car seat use",
        "Ergonomic principles and body mechanics when providing care",
        "Assessing balance and transfer ability before planning mobility care",
        "Safe use of equipment, and removing malfunctioning equipment from the care area",
        "Handling biohazardous, flammable and infectious materials",
        "Safe implementation of internal radiation therapy",
        "Restraints and safety devices: assessing appropriateness of the type used",
        "Following the legal and facility requirements that attach to restraint use",
        "Monitoring and evaluating the client's response to a restraint",
        "Acknowledging and documenting practice errors and near misses",
        "Incident, event and variance reporting, and evaluating the response to it",
        "Reporting, intervening in or escalating unsafe staff practice",
        "Emergency response: nursing roles in disaster planning and drills",
        "Deciding which clients can be discharged in a disaster situation",
        "Security plans: newborn security, controlled access, violence, environmental",
        "Triage and evacuation principles",
      ],
    },
    {
      title: "Health Promotion and Maintenance",
      rangeLabel: "6-12% of the exam",
      weight: 9,
      gate: "Given a client at any age, say what is expected for that stage, what screening is due, and what the teaching should target.",
      objectives: [
        "Expected age-related change, and the client's reaction to it",
        "Care and education from birth through 2 years",
        "Care and education for ages 3 through 17",
        "Care and education for the adult client aged 18 to 64",
        "Care and education for the adult client aged 65 and over",
        "Developmental stages and the transitions between them",
        "Prenatal care and education",
        "Assessing psychosocial response to pregnancy: support, perception, coping",
        "Calculating the expected delivery date",
        "Fetal heart rate at routine prenatal examinations",
        "Care of the antepartum client and the client in labor",
        "Postpartum care, and assessing for hemorrhage and infection",
        "Newborn care and education",
        "Comprehensive health assessment versus targeted screening",
        "Targeted screening: vision, nutrition, depression",
        "Health history and risk assessment, including family and genetic history",
        "Interviewing technique when taking a health history",
        "Choosing physical assessment equipment and technique appropriate to the client",
        "Disease prevention and health maintenance recommendations",
        "Community health education and participation in it",
        "High-risk behaviours: identifying them and teaching prevention and treatment",
        "Lifestyle choices, including sexuality, contraception and family planning",
        "Contraindications to a chosen contraceptive method",
        "Recognising the socially or environmentally isolated client",
        "Alternative and homeopathic practices the client is already using",
        "Assessing readiness to learn, learning preference, and barriers to learning",
        "Minimising communication barriers so teaching actually lands",
        "Self-care capacity in the home environment, and planning care around it",
        "Evaluating whether the client understood the health promotion behaviour taught",
      ],
    },
    {
      title: "Psychosocial Integrity",
      rangeLabel: "6-12% of the exam",
      weight: 9,
      gate: "Given a client in distress, choose the response that opens the conversation rather than closing it -- and recognise when distress has become a safety problem.",
      objectives: [
        "Therapeutic communication technique, and what makes a response non-therapeutic",
        "Encouraging the client to put feelings into words",
        "Allowing silence and time rather than filling it",
        "Assessing verbal and nonverbal communication needs",
        "Recognising nonverbal cues to physical and psychological stress",
        "Evaluating whether communication with the client was effective",
        "Assessing for abuse or neglect, and reporting or escalating it",
        "Risk factors for domestic, child, elder and sexual abuse",
        "Providing a safe environment for the abused or neglected client",
        "Assessing the potential for violence and using safety precautions",
        "Identifying the client in crisis and applying crisis intervention technique",
        "Coping mechanisms, and evaluating constructive use of defence mechanisms",
        "Adapting to temporary and permanent role change",
        "Supporting the client with an unexpected altered body image",
        "Substance use disorder: assessing for misuse, dependency and withdrawal",
        "Managing withdrawal and toxicity symptoms",
        "Non-substance dependencies such as gambling",
        "Signs and symptoms of acute and chronic mental illness",
        "Impaired cognition: memory loss, poor hygiene, altered judgment",
        "Alterations in mood, judgment, cognition and reasoning",
        "Behavioural intervention and helping the client regain self-control",
        "Orienting the client to reality, and providing reality-based diversion",
        "Sensory and perceptual alterations, and strategies for the client experiencing them",
        "Grief and loss, including anticipatory grieving",
        "Expected reactions to grief, and resources for bereavement",
        "End-of-life needs: fear, loss of control, financial concern, role change",
        "Psychosocial support for the family and caregiver at end of life",
        "Cultural practice and belief incorporated into the plan of care",
        "Religious and spiritual influences, including conflict between belief and treatment",
        "Family dynamics, stressors and barriers to family functioning",
        "Support systems, and involving the client in decisions about care",
        "Stress management technique, and evaluating the client's use of it",
        "Promoting and maintaining a therapeutic environment",
      ],
    },
    {
      title: "Basic Care and Comfort",
      rangeLabel: "6-12% of the exam",
      weight: 9,
      gate: "Given a client who cannot fully care for themselves, provide the assistance the deficit actually calls for while keeping dignity intact.",
      objectives: [
        "Assessing performance of activities of daily living and assisting where needed",
        "Maintaining dignity and privacy during personal care",
        "Personal hygiene for the dependent client",
        "Assistive devices: prosthetic limbs, hearing aids, eating utensils",
        "Compensating for a physical or sensory impairment",
        "Applying, maintaining and removing orthopedic devices",
        "Mobility and immobility, and the complications immobility causes",
        "Measures that promote circulation: range of motion, positioning, mobilisation",
        "Skin assessment and maintaining skin and tissue integrity",
        "Nutrition and oral hydration, and evaluating nutritional status",
        "Providing nutrition through tube feedings",
        "Evaluating intake and output and acting on the imbalance",
        "Bowel and bladder elimination, and managing an alteration in either",
        "Performing irrigations of bladder, ear or eye",
        "Rest and sleep: assessing the pattern and intervening on it",
        "Assessing for pain and acting on the assessment",
        "Nonpharmacological comfort measures",
        "Complementary therapies: potential benefit and contraindication",
        "Postmortem care",
      ],
    },
    {
      title: "Pharmacological and Parenteral Therapies",
      rangeLabel: "13-19% of the exam",
      weight: 16,
      gate: "Given an order, a client and a calculation, give the medication safely -- or refuse to, for a reason you can name.",
      objectives: [
        "The rights of medication administration, applied rather than recited",
        "Reviewing contraindications, allergies, lab results and interactions before giving",
        "Evaluating whether the medication order is appropriate and accurate for this client",
        "Performing the calculations medication administration requires",
        "Administering and documenting medications by common routes",
        "Administering and documenting medications by parenteral routes",
        "Mixing medications from two vials",
        "Titrating a dose against assessment and ordered parameters",
        "High-risk medications and the extra handling they require",
        "Controlled substances within regulatory guidelines",
        "Safe storage and safe disposal of medication",
        "Medication reconciliation and the nurse's part in it",
        "Expected actions and outcomes of a prescribed medication",
        "Evaluating the client's response to a medication over time",
        "Adverse effects, side effects, contraindications and interactions distinguished",
        "Recognising an allergic reaction to a medication",
        "Incompatibilities among a client's prescribed medications",
        "Notifying the provider, and documenting what was observed and done",
        "Teaching the client which effects warrant a call to the provider",
        "Pharmacological pain management, including p.r.n. decision-making",
        "Pain medication appropriate to age and diagnosis, including pregnancy and older adults",
        "Evaluating and documenting response to pain medication",
        "Peripheral intravenous therapy: vein selection and site maintenance",
        "Preparing the client for venous access device insertion",
        "Monitoring an infusion pump, including patient-controlled analgesia",
        "Central venous access devices: access, maintenance and client teaching",
        "Blood and blood products: identification, consent and crossmatch verification",
        "Venous access adequate for blood product administration",
        "Administering blood products and evaluating the response",
        "Total parenteral nutrition: administration and client teaching",
        "TPN complications: hyperglycemia, fluid imbalance, infection",
      ],
    },
    {
      title: "Reduction of Risk Potential",
      rangeLabel: "9-15% of the exam",
      weight: 12,
      gate: "Given a client before or after a procedure, name the complication most likely to develop and the finding that would announce it.",
      objectives: [
        "Assessing and responding to changes and trends in vital signs",
        "Applying pathophysiology when measuring and interpreting vital signs",
        "Comparing client laboratory values against normal values",
        "Monitoring laboratory values and notifying the provider about results",
        "Obtaining blood specimens, and specimens other than blood",
        "Teaching the client the purpose and procedure of an ordered test",
        "Caring for the client undergoing diagnostic testing",
        "Comparing diagnostic findings against pretest results",
        "Testing within the nurse's scope: ECG, point-of-care testing, fetal monitoring",
        "Monitoring maternal and fetal diagnostic tests",
        "Potential for aspiration: feeding tube, sedation, swallowing difficulty",
        "Potential for skin breakdown: immobility, nutrition, incontinence",
        "Risk of insufficient vascular perfusion",
        "Comparing current data against the client's own baseline",
        "Monitoring output for change from baseline",
        "Focused and system-specific assessment",
        "Abnormal peripheral pulses after a procedure",
        "Abnormal neurologic status: consciousness, muscle strength, mobility",
        "Peripheral edema, and signs of hypo- or hyperglycemia",
        "Factors that delay wound healing",
        "Risk assessment for falls, sensory impairment, mobility and skin integrity",
        "Recognising a trend in the client's condition and intervening on it",
        "Abnormal response following a diagnostic test or procedure",
        "Monitoring for signs of bleeding",
        "Positioning to prevent complications after a procedure",
        "Inserting, maintaining and removing a nasogastric or oral gastrointestinal tube",
        "Inserting, maintaining and removing a urinary catheter",
        "Inserting, maintaining and removing a peripheral intravenous line",
        "Maintaining tube patency, including chest tubes and decompression tubes",
        "Maintaining a percutaneous feeding tube",
        "Devices that promote venous return: antiembolism stockings, compression devices",
        "Intervening on circulatory complications: hemorrhage, embolus, shock",
        "Preventing aspiration, including verifying tube placement",
        "Preventing neurologic complications such as footdrop and numbness",
        "Recovery from local, regional and general anesthesia",
        "Preoperative care, and preoperative and postoperative teaching",
        "Managing the client before, during and after moderate sedation",
        "Monitoring therapeutic devices: chest tube, drains, continuous bladder irrigation",
        "Moving a client with a musculoskeletal condition without further injury",
        "Evaluating the client's response to a procedure or treatment",
      ],
    },
    {
      title: "Physiological Adaptation",
      rangeLabel: "11-17% of the exam",
      weight: 14,
      gate: "Given a client whose condition is changing, connect the pathophysiology to the finding in front of you and act at the right moment.",
      objectives: [
        "General principles of pathophysiology: injury and repair, immunity, cellular structure",
        "Identifying the pathophysiology behind an acute or chronic condition",
        "Assessing the client's adaptation to illness or health alteration",
        "Fluid and electrolyte imbalance: recognising the signs and symptoms",
        "Managing the client with a fluid or electrolyte imbalance",
        "Evaluating the response to correction of an imbalance",
        "Decreased cardiac output: diminished pulses, hypotension",
        "Cardiac rhythm strip abnormalities and what they signify",
        "Hemodynamic values and intervening on abnormal ones",
        "Managing care of the client on telemetry or with a pacing device",
        "Monitoring and maintaining arterial lines",
        "Hemodialysis, continuous renal replacement therapy and peritoneal dialysis",
        "Managing the client with impaired ventilation or oxygenation",
        "Monitoring and caring for the client on a ventilator",
        "Performing suctioning, and providing pulmonary hygiene",
        "Wound care, dressing change, and monitoring wounds for infection",
        "Managing drainage devices, including negative pressure wound therapy",
        "Ostomy care and client education",
        "Removing sutures or staples",
        "Postoperative care and evaluating the response to surgery",
        "Caring for the client with increased intracranial pressure",
        "Internal monitoring devices: intracranial pressure, intrauterine pressure",
        "Care of the client who has had a seizure",
        "Infectious disease: signs, symptoms and incubation periods",
        "Evaluating response to treatment for an infectious disease",
        "Adverse effects of radiation therapy and interventions for them",
        "Implementing and monitoring phototherapy",
        "Maintaining the client's optimal temperature",
        "Complications of pregnancy, labor and delivery: eclampsia, hemorrhage, precipitous labor",
        "Signs of potential prenatal complications",
        "Assisting with invasive procedures: central line, thoracentesis, bronchoscopy",
        "Medical emergencies: applying pathophysiology under time pressure",
        "Emergency care procedures, including wound dehiscence",
        "Identifying client data that must be reported immediately",
        "Notifying the provider about an unexpected response or emergency",
        "Unexpected adverse response to therapy, and recognising complications early",
        "Evaluating achievement of the client's treatment goals",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// NCLEX-PN (2026 Test Plan, effective April 1 2026 through March 31 2029)
// Client Needs midpoints: 21 / 13 / 9 / 12 / 10 / 13 / 12 / 10.
//
// Not a smaller NCLEX-RN. The PN plan differs in ways that are scope of
// practice rather than difficulty, and the differences are the point:
//   - "Coordinated Care", not "Management of Care". The PN contributes to
//     care coordination under supervision rather than owning it.
//   - "Data Collection", not "Assessment". The RN assesses; the PN collects
//     data and reports it. Blurring this teaches practice that is outside
//     the licence.
//   - "Pharmacological Therapies", not "Pharmacological and Parenteral
//     Therapies". Blood products, central venous access and total parenteral
//     nutrition are absent here, and deliberately so.
//   - Psychosocial Integrity is weighted higher on the PN exam (12%) than on
//     the RN exam (9%).
// ---------------------------------------------------------------------------
export const NCLEX_PN_TRACK: SeedTrack = {
  code: "NCLEXPN",
  title: "NCLEX-PN Coach",
  description:
    "The practical and vocational nurse licensure examination, built on the 2026 NCSBN test plan. Weighted as the exam weights it, and scoped as the licence is scoped -- what the PN collects, reports and contributes, rather than what the RN decides.",
  trackType: "certification",
  subcategorySlug: "nclex-preparation",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://www.ncsbn.org/public-files/2026_PN_Test%20Plan-F.pdf",
  sourceVerifiedAt: VERIFIED_AT,
  requiresAcknowledgement: true,
  disclaimerKey: NURSING_DISCLAIMER_KEY,
  disclaimerVersion: 1,
  credential: {
    ...NCSBN_PROVIDER,
    credentialSlug: "nclex-pn",
    credentialName: "NCLEX-PN Examination",
    credentialUrl: "https://www.ncsbn.org/exams/testplans.page",
    basis: "regulatory_licensure",
    examCode: "NCLEX-PN",
    examRevision: "2026 Test Plan",
    standardName: "NCLEX-PN Test Plan",
    standardRevision: "2026",
    status: "active",
    effectiveDate: "2026-04-01",
    retirementDate: "2029-03-31",
    officialObjectivesUrl:
      "https://www.ncsbn.org/public-files/2026_PN_Test%20Plan-F.pdf",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "Completion of a state-approved practical or vocational nursing program. Measured against what a newly licensed PN/VN must do safely under the direction of an RN or provider.",
    questionFormat:
      "Computerized adaptive, variable length; includes clinical judgment items alongside multiple choice, multiple response and other formats",
    passingScorePolicy:
      "Pass/fail against a standard set by NCSBN rather than a percentage score; decided by the 95% confidence interval rule, the maximum-length rule, or the run-out-of-time rule",
  },
  units: [
    {
      title: "Coordinated Care",
      rangeLabel: "18-24% of the exam",
      weight: 21,
      gate: "Given a shift and a set of clients, act inside the PN scope: know what you may accept, what you must pass to the RN, and what you report rather than decide.",
      objectives: [
        "What the practical nurse licence permits, and where it stops",
        "Accepting an assignment, and declining one that exceeds scope or competence",
        "Assignment and delegation as they apply to the PN, including delegation to assistive personnel",
        "Reporting to the registered nurse: what must be escalated rather than handled",
        "Establishing priorities among assigned clients",
        "Recognising the client whose condition requires immediate RN or provider involvement",
        "Contributing to the plan of care rather than authoring it",
        "Continuity of care and handoff of assigned clients",
        "Admission, transfer and discharge procedures",
        "Advance directives, and the client's right to self-determination",
        "Acting as client advocate within the PN role",
        "Client rights, and educating clients and staff about them",
        "Informed consent: what the PN may and may not do in the process",
        "Confidentiality and information security, including social media disclosure",
        "Ethical practice and recognising an ethical dilemma",
        "Legal rights and responsibilities, including refusal of treatment",
        "Mandatory reporting: abuse, neglect, communicable disease",
        "Documenting accurately, completely and in approved terminology",
        "Information technology and appropriate access to client records",
        "Receiving and verifying provider orders within scope",
        "Collaborating with the interdisciplinary team",
        "The referral process and the PN's part in it",
        "Resource management and cost-conscious care",
        "Performance and quality improvement participation",
        "Concepts of management and supervision as they apply to the PN",
        "Recognising the limits of one's own competence and using resources",
      ],
    },
    {
      title: "Safety and Infection Prevention and Control",
      rangeLabel: "10-16% of the exam",
      weight: 13,
      gate: "Given a client and an environment, apply the right precautions and use the least restrictive option that keeps the client safe.",
      objectives: [
        "Principles of infection prevention: hand hygiene, aseptic and sterile technique",
        "Standard precautions applied to every client",
        "Transmission-based precautions: airborne, droplet, contact",
        "Surgical asepsis and maintaining a sterile field",
        "Caring for the immunocompromised client",
        "Communicable disease reporting procedure",
        "Educating client and staff on infection prevention",
        "Correct client identification before care",
        "Client allergies: collecting the data and acting on it",
        "Accident, error and injury prevention",
        "Factors raising injury risk: age, developmental stage, mental status",
        "Deficits that impede safety: visual, hearing, sensory",
        "Seizure precautions",
        "Home safety, including fire and environmental hazards",
        "Ergonomic principles and safe client handling",
        "Safe use of equipment and removing faulty equipment from use",
        "Handling hazardous and infectious materials",
        "Least restrictive restraints and safety devices: choosing the least restrictive option",
        "Legal and facility requirements attached to restraint use",
        "Monitoring and evaluating the client in restraints",
        "Incident, event and variance reporting",
        "Acknowledging and documenting errors and near misses",
        "Emergency response plans and participation in drills",
        "Security plans: newborn security, controlled access, violence",
      ],
    },
    {
      title: "Health Promotion and Maintenance",
      rangeLabel: "6-12% of the exam",
      weight: 9,
      gate: "Given a client at any life stage, collect the right data, recognise what is expected for that stage, and reinforce the teaching.",
      objectives: [
        "Data collection technique, and how it differs from assessment",
        "Collecting a health history and reporting the findings",
        "Choosing the right technique and equipment for the client's age",
        "Expected age-related changes across the lifespan",
        "Developmental stages and the transitions between them",
        "Care of the newborn, infant and toddler",
        "Care of the preschool, school-age and adolescent client",
        "Care of the adult client",
        "Care of the older adult client",
        "Antepartum care and data collection",
        "Care of the client in labor",
        "Postpartum care, including signs of hemorrhage and infection",
        "Newborn care and feeding",
        "Health promotion and disease prevention teaching",
        "Reinforcing teaching the RN has planned",
        "High-risk behaviours and teaching about them",
        "Lifestyle choices, including family planning and sexuality",
        "Self-care capacity and managing care in the home",
        "Community resources available to the client",
      ],
    },
    {
      title: "Psychosocial Integrity",
      rangeLabel: "9-15% of the exam",
      weight: 12,
      gate: "Given a client in distress, respond therapeutically, and recognise when distress has become a safety problem to escalate.",
      objectives: [
        "Therapeutic communication technique, and what makes a response non-therapeutic",
        "Encouraging the client to express feelings",
        "Recognising nonverbal cues to distress",
        "Abuse or neglect: recognising it, reporting it, escalating it",
        "Risk factors for domestic, child and elder abuse",
        "Recognising the potential for violence and using safety precautions",
        "Crisis intervention within the PN role",
        "Coping mechanisms and adaptation to role change",
        "Supporting the client with an altered body image",
        "Substance use disorder, dependency and withdrawal",
        "Recognising signs of withdrawal or toxicity and reporting them",
        "Non-substance dependencies",
        "Mental health concepts and recognising acute and chronic mental illness",
        "Impaired cognition: memory loss, altered judgment, poor hygiene",
        "Behavioural management technique",
        "Orienting the client to reality",
        "Sensory and perceptual alterations",
        "Grief, loss and anticipatory grieving",
        "End-of-life care concepts and comfort at end of life",
        "Supporting the family and caregiver",
        "Cultural awareness and incorporating cultural practice into care",
        "Religious and spiritual influences on health",
        "Support systems and involving them in care",
        "Stress management technique",
        "Maintaining a therapeutic environment",
      ],
    },
    {
      title: "Basic Care and Comfort",
      rangeLabel: "7-13% of the exam",
      weight: 10,
      gate: "Given a client who cannot fully care for themselves, provide the assistance the deficit calls for while keeping dignity intact.",
      objectives: [
        "Activities of daily living and assisting where the client cannot",
        "Maintaining dignity and privacy during personal care",
        "Personal hygiene, including oral and perineal care",
        "Assistive devices and prostheses",
        "Compensating for a physical or sensory impairment",
        "Mobility and immobility, and the complications of immobility",
        "Positioning, range of motion and promoting circulation",
        "Safe transfer and ambulation",
        "Skin care and maintaining tissue integrity",
        "Nutrition and oral hydration",
        "Assisting with feeding, and tube feeding within scope",
        "Monitoring and recording intake and output",
        "Bowel and bladder elimination",
        "Catheter care and ostomy care",
        "Performing irrigations within scope",
        "Rest and sleep patterns",
        "Collecting data about pain and reporting it",
        "Nonpharmacological comfort interventions",
        "Postmortem care",
      ],
    },
    {
      title: "Pharmacological Therapies",
      rangeLabel: "10-16% of the exam",
      weight: 13,
      gate: "Given an order and a client, give the medication safely within the PN scope -- or stop and report the reason you cannot.",
      objectives: [
        "The rights of medication administration, applied rather than recited",
        "Checking contraindications, allergies and interactions before giving",
        "Performing dosage calculations accurately",
        "Converting between units of measurement",
        "Administering medication by oral and topical routes",
        "Administering medication by intramuscular, subcutaneous and intradermal routes",
        "Routes and procedures that fall outside the PN scope in most jurisdictions",
        "Documenting medication administration",
        "Expected actions and therapeutic outcomes",
        "Side effects, adverse effects, contraindications and interactions distinguished",
        "Recognising an allergic reaction and responding to it",
        "Reporting adverse effects to the registered nurse or provider",
        "Monitoring the client's response to a medication",
        "Pharmacological pain management and p.r.n. decisions within scope",
        "Evaluating and documenting the response to pain medication",
        "Controlled substances: handling, counting and documentation",
        "Safe storage and disposal of medication",
        "Maintaining an intravenous site and recognising infiltration or phlebitis",
        "Reinforcing medication teaching with the client",
      ],
    },
    {
      title: "Reduction of Risk Potential",
      rangeLabel: "9-15% of the exam",
      weight: 12,
      gate: "Given a client before or after a procedure, collect the data that would show a complication developing, and report it in time.",
      objectives: [
        "Collecting vital signs and recognising changes and trends",
        "Reporting an abnormal vital sign rather than acting alone on it",
        "Comparing laboratory values against normal values",
        "Monitoring laboratory results and reporting them",
        "Collecting blood and non-blood specimens",
        "Preparing the client for a diagnostic test",
        "Caring for the client during and after diagnostic testing",
        "Testing within the PN scope, including point-of-care testing",
        "Potential for aspiration and preventing it",
        "Potential for skin breakdown and preventing it",
        "Risk of insufficient vascular perfusion",
        "Comparing current data against the client's baseline",
        "Monitoring output for change from baseline",
        "Focused data collection on a body system",
        "Recognising abnormal neurologic status",
        "Recognising peripheral edema and abnormal pulses",
        "Signs of hypoglycemia and hyperglycemia",
        "Factors that delay wound healing",
        "Risk assessment for falls and mobility",
        "Therapeutic procedures and the PN's role in them",
        "Care before and after surgery, and reinforcing preoperative teaching",
        "Recovery from anesthesia and what to watch for",
        "Maintaining tubes and drains, including patency",
        "Devices that promote venous return",
        "Preventing neurologic complications of immobility",
        "Evaluating and reporting the client's response to a procedure",
      ],
    },
    {
      title: "Physiological Adaptation",
      rangeLabel: "7-13% of the exam",
      weight: 10,
      gate: "Given a client whose condition is changing, connect basic pathophysiology to what you are seeing and escalate at the right moment.",
      objectives: [
        "Basic pathophysiology: injury and repair, immunity, cellular structure",
        "Connecting a chronic condition to the findings it produces",
        "Alterations in body systems and the care they require",
        "Fluid and electrolyte imbalance: recognising and reporting it",
        "Caring for the client with a fluid or electrolyte imbalance",
        "Monitoring the client with impaired oxygenation",
        "Oxygen therapy and airway care within scope",
        "Performing suctioning",
        "Caring for the client with a tracheostomy",
        "Wound care and dressing changes",
        "Monitoring wounds for signs of infection",
        "Managing drainage devices",
        "Ostomy care and reinforcing client teaching",
        "Postoperative care and recognising complications",
        "Infectious disease: signs, symptoms and incubation periods",
        "Caring for the client receiving radiation or chemotherapy",
        "Maintaining the client's optimal temperature",
        "Complications of pregnancy and delivery to recognise and report",
        "Medical emergencies and the PN's immediate response",
        "Identifying client data that must be reported immediately",
        "Unexpected response to therapy, and recognising complications early",
        "Reporting a change in condition to the registered nurse or provider",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// A note on unit weights for the tracks below.
//
// On the NCLEX tracks above, `weight` is a vendor fact: NCSBN publishes those
// percentages and the exam is built to them. Nothing below has an equivalent.
// Federal regulation sets a 75-hour floor for nurse aide training without
// apportioning it, and the AACN Essentials define domains without weighting
// them. So the weights on these four tracks are our own judgment about study
// emphasis, and must not be presented to a learner as an exam blueprint.
// ---------------------------------------------------------------------------

const CMS_PROVIDER = {
  providerSlug: "cms",
  providerName: "Centers for Medicare & Medicaid Services",
  providerUrl: "https://www.cms.gov/",
  subcategorySlug: "nursing-licensure",
  credentialType: "certification",
} as const;

const AACN_PROVIDER = {
  providerSlug: "aacn-nursing",
  providerName: "American Association of Colleges of Nursing",
  providerUrl: "https://www.aacnnursing.org/",
  subcategorySlug: "nursing-degrees",
  credentialType: "degree",
} as const;

// ---------------------------------------------------------------------------
// Certified Nursing Assistant.
//
// The federal floor is 42 CFR 483.152: at least 75 clock hours, of which at
// least 16 must be supervised practical training, and at least 16 hours must
// cover the paragraph (b)(1) topics BEFORE any contact with a resident. The
// seven content areas below are the ones the regulation enumerates.
//
// States may and do require more than the federal floor, and the competency
// evaluation itself is state-administered, which is why this credential is
// recorded as regulatory licensure against a standard rather than an exam.
// ---------------------------------------------------------------------------
export const CNA_TRACK: SeedTrack = {
  code: "CNA",
  title: "Certified Nursing Assistant Coach",
  description:
    "Nurse aide training built on the federal requirements at 42 CFR 483.152 -- the sixteen hours that must come before you ever touch a resident, then basic nursing and personal care skills, cognition, restorative services and residents' rights.",
  trackType: "certification",
  subcategorySlug: "nursing-licensure",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://www.ecfr.gov/current/title-42/section-483.152",
  sourceVerifiedAt: VERIFIED_AT,
  requiresAcknowledgement: true,
  disclaimerKey: NURSING_DISCLAIMER_KEY,
  disclaimerVersion: 1,
  credential: {
    ...CMS_PROVIDER,
    credentialSlug: "certified-nursing-assistant",
    credentialName: "Certified Nursing Assistant (Nurse Aide)",
    credentialUrl: "https://www.ecfr.gov/current/title-42/section-483.152",
    basis: "regulatory_licensure",
    standardName: "42 CFR 483.152 -- Requirements for approval of a nurse aide training and competency evaluation program",
    standardRevision: "Current as of 2026-09-18",
    status: "active",
    officialObjectivesUrl: "https://www.ecfr.gov/current/title-42/section-483.152",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "No prior healthcare experience assumed. Certification requires completing a state-approved program and passing a state competency evaluation; your state may require more than the 75-hour federal minimum.",
    questionFormat:
      "State-administered competency evaluation, typically a written or oral examination plus a skills demonstration",
    passingScorePolicy:
      "Set by each state's nurse aide registry, not federally; both the knowledge and skills portions must be passed",
  },
  units: [
    {
      title: "Before resident contact",
      rangeLabel: "At least 16 hours, federally required first",
      weight: 18,
      gate: "Demonstrate the five things federal law says you must know before you are allowed near a resident at all.",
      objectives: [
        "Why this block exists: federal law bars resident contact until it is complete",
        "Communication and interpersonal skills with residents",
        "Communicating with families and with the care team",
        "Infection control: hand hygiene as the single highest-value habit",
        "Standard precautions and personal protective equipment",
        "Safety and emergency procedures",
        "The Heimlich maneuver, named explicitly in the regulation",
        "Recognising an emergency and summoning help correctly",
        "Promoting residents' independence rather than doing for them",
        "Respecting residents' rights in everyday interaction",
      ],
    },
    {
      title: "Basic nursing skills",
      rangeLabel: "42 CFR 483.152(b)(2)",
      weight: 18,
      gate: "Take an accurate set of measurements, notice when something has changed, and report it to the nurse without editorialising.",
      objectives: [
        "Taking and recording temperature, pulse, respiration and blood pressure",
        "Recognising a measurement that falls outside the expected range",
        "Measuring and recording height and weight",
        "Caring for the resident's environment: bed, unit, call light within reach",
        "Bed making, occupied and unoccupied",
        "Recognising abnormal changes in body functioning",
        "Reporting changes to the nurse: what, when and in what words",
        "Observation versus interpretation, and why the aide reports the first",
        "Caring for residents when death is imminent",
        "Supporting the family of a dying resident",
        "Documenting care accurately and within scope",
      ],
    },
    {
      title: "Personal care skills",
      rangeLabel: "42 CFR 483.152(b)(3)",
      weight: 20,
      gate: "Provide personal care that is clean, safe and unhurried, and that leaves the resident's dignity intact.",
      objectives: [
        "Bathing: bed bath, shower and tub, and water temperature safety",
        "Grooming, including mouth care and denture care",
        "Hair and nail care within scope",
        "Shaving safely",
        "Dressing, including a resident with a weak or affected side",
        "Toileting, bedpan and urinal use",
        "Incontinence care and protecting skin",
        "Assisting with eating and hydration",
        "Proper feeding techniques and reducing aspiration risk",
        "Recognising and reporting poor intake",
        "Skin care and recognising early pressure injury",
        "Transfers, positioning and turning",
        "Using a gait belt and a mechanical lift safely",
        "Protecting the resident's privacy throughout personal care",
      ],
    },
    {
      title: "Mental health and social service needs",
      rangeLabel: "42 CFR 483.152(b)(4)",
      weight: 13,
      gate: "Respond to a resident's behavior by changing your own approach first, rather than managing the resident.",
      objectives: [
        "Modifying your own behavior in response to a resident's behavior",
        "Developmental tasks associated with the aging process",
        "Responding to behavior without escalating it",
        "Allowing residents to make their own choices",
        "Behavior that maintains and enhances the resident's dignity",
        "Using the resident's family as a source of emotional support",
        "Recognising depression and withdrawal, and reporting it",
        "Cultural and religious practices that shape daily care",
        "Sexuality and the older adult resident",
      ],
    },
    {
      title: "Care of cognitively impaired residents",
      rangeLabel: "42 CFR 483.152(b)(5)",
      weight: 13,
      gate: "Meet a resident with dementia where they are: reduce the demand, not the person.",
      objectives: [
        "Needs and behaviors of residents with dementia, Alzheimer's and other causes",
        "Communicating with a cognitively impaired resident",
        "Understanding behavior as communication rather than defiance",
        "Appropriate responses to behavior, including agitation and resistance",
        "Methods of reducing the effects of cognitive impairment",
        "Consistent routine, orientation cues and a calm environment",
        "Wandering and exit-seeking: keeping a resident safe without restraint",
        "Sundowning and adjusting the approach late in the day",
        "Supporting the family of a resident with dementia",
      ],
    },
    {
      title: "Basic restorative services",
      rangeLabel: "42 CFR 483.152(b)(6)",
      weight: 10,
      gate: "Help a resident keep or regain function, matching the help to what they can still do for themselves.",
      objectives: [
        "Teaching self-care according to the resident's own ability",
        "Assistive devices for transferring, ambulation, eating and dressing",
        "Maintaining range of motion, active and passive",
        "Proper turning and positioning in bed and in a chair",
        "Bowel and bladder training",
        "Care and use of prosthetic and orthotic devices",
        "Ambulation with a walker, cane or crutches",
        "Recognising when a device fits poorly or is unsafe",
      ],
    },
    {
      title: "Residents' rights",
      rangeLabel: "42 CFR 483.152(b)(7)",
      weight: 8,
      gate: "Name what a resident is entitled to, and what you must do the moment you suspect it has been violated.",
      objectives: [
        "Providing privacy and maintaining confidentiality",
        "Supporting each resident's right to make personal choices",
        "Assisting in resolving grievances and disputes",
        "Helping residents take part in resident and family groups and activities",
        "Care and security of residents' personal possessions",
        "Freedom from abuse, mistreatment and neglect",
        "Recognising abuse and neglect, including neglect by omission",
        "Reporting a suspected violation to the right facility staff, promptly",
        "Avoiding the need for restraints in line with current professional standards",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Practical / vocational nursing program.
//
// Distinct from the NCLEX-PN track above: that one prepares for the
// examination, this one is the program that precedes it. The content
// authority is the same NCSBN plan (it defines what entry-level PN practice
// is) plus the scope of practice each state's nurse practice act sets.
// ---------------------------------------------------------------------------
export const LPN_TRACK: SeedTrack = {
  code: "LPNVN",
  title: "Practical Nursing (LPN/LVN) Coach",
  description:
    "The practical nursing program from the beginning: foundations, the skills you are licensed to perform, the medical-surgical body of knowledge, and the scope question that sits under all of it -- what the PN does, and what the PN reports.",
  trackType: "certification",
  subcategorySlug: "nursing-licensure",
  freshnessModel: "certification_aligned",
  sourceUrl: "https://www.ncsbn.org/public-files/2026_PN_Test%20Plan-F.pdf",
  sourceVerifiedAt: VERIFIED_AT,
  requiresAcknowledgement: true,
  disclaimerKey: NURSING_DISCLAIMER_KEY,
  disclaimerVersion: 1,
  credential: {
    ...NCSBN_PROVIDER,
    subcategorySlug: "nursing-licensure",
    credentialSlug: "practical-nurse-licence",
    credentialName: "Licensed Practical / Vocational Nurse",
    credentialUrl: "https://www.ncsbn.org/nursing-regulation/licensure.page",
    basis: "regulatory_licensure",
    standardName: "State-approved practical nursing program and nurse practice act, with NCLEX-PN as the licensure examination",
    standardRevision: "2026",
    status: "active",
    officialObjectivesUrl: "https://www.ncsbn.org/public-files/2026_PN_Test%20Plan-F.pdf",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "Entry point for the program itself; no prior nursing education assumed. Licensure requires graduating a state-approved program and passing NCLEX-PN.",
    questionFormat: "Program coursework and clinical evaluation; licensure is by NCLEX-PN",
    passingScorePolicy: "Set by the program and the state board of nursing",
  },
  units: [
    {
      title: "Foundations of practical nursing",
      weight: 16,
      gate: "Say what the practical nurse licence authorises, and route a situation correctly when it sits outside that line.",
      objectives: [
        "The practical nurse role within the healthcare team",
        "Scope of practice, and why it is set by your state's nurse practice act",
        "Data collection versus assessment, and why the distinction is legal, not semantic",
        "Working under the direction of an RN or provider",
        "Accepting, refusing and clarifying an assignment",
        "The nursing process and the PN's contribution to each stage",
        "Documentation standards and legal record-keeping",
        "Confidentiality and privacy obligations",
        "Professional boundaries with residents, patients and families",
        "Ethical principles applied to everyday practice",
        "Delegation to unlicensed assistive personnel",
        "Communication with the interdisciplinary team",
        "Therapeutic communication with patients and families",
        "Cultural humility in care delivery",
      ],
    },
    {
      title: "Anatomy, physiology and basic pathophysiology",
      weight: 18,
      gate: "Connect a body system's normal function to the findings that appear when it fails.",
      objectives: [
        "Cell structure, tissue types and homeostasis",
        "Integumentary system: structure, function and common alterations",
        "Musculoskeletal system and common injuries and conditions",
        "Cardiovascular system: circulation, perfusion and common disease",
        "Respiratory system: ventilation, oxygenation and common disease",
        "Gastrointestinal system: digestion, absorption and elimination",
        "Renal and urinary systems, and fluid balance",
        "Endocrine system and the conditions that follow its disruption",
        "Nervous system: central, peripheral and autonomic",
        "Immune system, inflammation and the response to infection",
        "Reproductive systems across the lifespan",
        "Fluid, electrolyte and acid-base balance in plain terms",
        "How an acute illness differs from an exacerbation of a chronic one",
        "Medical terminology: roots, prefixes and suffixes",
      ],
    },
    {
      title: "Fundamental nursing skills",
      weight: 20,
      gate: "Perform the core skills safely, in order, and know the observation each one is meant to produce.",
      objectives: [
        "Hand hygiene, standard precautions and isolation technique",
        "Sterile technique and maintaining a sterile field",
        "Vital signs: taking them, and interpreting a change",
        "Height, weight and intake and output measurement",
        "Head-to-toe data collection",
        "Positioning, transferring and safe patient handling",
        "Range of motion and mobility assistance",
        "Personal hygiene and skin care",
        "Pressure injury prevention and staging awareness",
        "Wound care and dressing changes",
        "Specimen collection: urine, stool, sputum and blood",
        "Urinary catheter insertion and care",
        "Enteral feeding and tube care",
        "Ostomy care",
        "Oxygen delivery devices and airway care",
        "Suctioning technique",
        "Intravenous site monitoring and maintenance within scope",
        "Nutrition, diet types and assisting with meals",
        "Pain data collection and nonpharmacological comfort measures",
        "End-of-life and postmortem care",
      ],
    },
    {
      title: "Pharmacology and medication administration",
      weight: 18,
      gate: "Give a medication safely: right checks, right calculation, right route, and a clear reason to stop if anything does not line up.",
      objectives: [
        "Drug classifications and how a class predicts an effect",
        "Generic and trade names, and why the generic is safer to learn",
        "Pharmacokinetics in practical terms: absorption to excretion",
        "The rights of medication administration",
        "Dosage calculation and unit conversion",
        "Calculating pediatric and weight-based doses",
        "Oral, topical and transdermal administration",
        "Intramuscular, subcutaneous and intradermal injection technique",
        "Site selection and rotation",
        "Insulin administration and sliding scale orders",
        "Routes outside the PN scope in most jurisdictions",
        "Controlled substances: handling, counting and documentation",
        "Recognising side effects and adverse reactions",
        "Allergic and anaphylactic reactions",
        "Drug interactions, including food and herbal products",
        "High-alert medications and the extra checks they need",
        "Medication reconciliation and reinforcing medication teaching",
        "Documenting administration and refusal",
      ],
    },
    {
      title: "Medical-surgical nursing across the lifespan",
      weight: 18,
      gate: "Care for an adult with a common chronic or acute condition, and notice the complication before it announces itself.",
      objectives: [
        "Caring for the patient with hypertension and heart failure",
        "Angina, myocardial infarction and post-event care",
        "Peripheral vascular disease and venous insufficiency",
        "COPD and asthma management",
        "Pneumonia, influenza and tuberculosis precautions",
        "Diabetes mellitus: monitoring, hypo- and hyperglycemia",
        "Diabetic foot care and long-term complications",
        "Thyroid disorders",
        "Stroke care and rehabilitation support",
        "Seizure care and precautions",
        "Dementia and delirium distinguished",
        "Arthritis, osteoporosis and fracture care",
        "Post-surgical care and complication watch",
        "Cancer care, chemotherapy and radiation side effects",
        "Renal failure and dialysis support",
        "Gastrointestinal disorders and ostomy patients",
        "Infection, sepsis and recognising early deterioration",
        "Care of the older adult and polypharmacy",
      ],
    },
    {
      title: "Maternal, newborn, pediatric and mental health nursing",
      weight: 10,
      gate: "Adjust care to the patient in front of you -- a labouring mother, a toddler, an adolescent in crisis -- rather than applying the adult default.",
      objectives: [
        "Antepartum care and common discomforts of pregnancy",
        "Danger signs in pregnancy that must be reported",
        "Care of the client in labor and delivery",
        "Postpartum care and hemorrhage recognition",
        "Newborn care, feeding and normal findings",
        "Growth and development milestones by age",
        "Pediatric vital sign and dosage differences",
        "Common childhood illnesses and immunisation schedules",
        "Communicating with a child and with the parent",
        "Child abuse recognition and mandatory reporting",
        "Mental health conditions commonly encountered",
        "Anxiety, depression and suicide risk recognition",
        "Substance use, withdrawal and overdose recognition",
        "De-escalation and therapeutic environment",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Associate Degree in Nursing (prelicensure RN).
//
// The content target is entry-level registered nurse practice, which NCSBN
// defines in the RN test plan; the degree itself is awarded by an accredited
// program. Both are recorded: the standard is the program accreditation, the
// examination the graduate sits is NCLEX-RN.
// ---------------------------------------------------------------------------
export const ADN_TRACK: SeedTrack = {
  code: "ADNRN",
  title: "Associate Degree Nursing (RN) Coach",
  description:
    "The prelicensure RN program: the sciences underneath practice, the full nursing process with the RN's own assessment authority, medical-surgical depth, and the specialty rotations -- aimed at entry-level RN practice as NCSBN defines it.",
  trackType: "graduate",
  subcategorySlug: "nursing-degrees",
  freshnessModel: "academic_foundational",
  sourceUrl: "https://www.ncsbn.org/public-files/2026_RN_Test%20Plan_English-F.pdf",
  sourceVerifiedAt: VERIFIED_AT,
  requiresAcknowledgement: true,
  disclaimerKey: NURSING_DISCLAIMER_KEY,
  disclaimerVersion: 1,
  credential: {
    ...NCSBN_PROVIDER,
    subcategorySlug: "nursing-degrees",
    credentialSlug: "associate-degree-nursing",
    credentialName: "Associate Degree in Nursing (Registered Nurse)",
    credentialUrl: "https://www.ncsbn.org/nursing-regulation/licensure.page",
    basis: "accreditation_standard",
    standardName: "Accredited prelicensure RN program, with NCLEX-RN as the licensure examination",
    standardRevision: "2026",
    status: "active",
    officialObjectivesUrl: "https://www.ncsbn.org/public-files/2026_RN_Test%20Plan_English-F.pdf",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "Program prerequisites usually include anatomy and physiology, microbiology and college-level mathematics. Licensure requires graduating an approved program and passing NCLEX-RN.",
    questionFormat: "Program coursework, clinical evaluation and standardised progression testing",
    passingScorePolicy: "Set by the program; licensure is by NCLEX-RN",
  },
  units: [
    {
      title: "Professional nursing foundations",
      weight: 14,
      gate: "Act as the nurse who owns the assessment: gather it, interpret it, and be accountable for the judgment that follows.",
      objectives: [
        "The registered nurse role and its accountability",
        "Scope of practice and the state nurse practice act",
        "The nursing process: assessment, diagnosis, planning, implementation, evaluation",
        "Nursing assessment as an RN act, distinct from data collection",
        "Formulating a nursing diagnosis from assessment findings",
        "Setting measurable, client-centred outcomes",
        "Clinical judgment and the steps that make it a process rather than instinct",
        "Prioritisation frameworks and their limits",
        "Delegation and supervision: the five rights applied",
        "Legal and ethical accountability, including negligence and malpractice",
        "Informed consent and the nurse's distinct role in it",
        "Documentation, reporting and handoff communication",
        "Evidence-based practice and reading a clinical guideline",
        "Patient safety, error disclosure and just culture",
      ],
    },
    {
      title: "Health assessment and the sciences underneath practice",
      weight: 16,
      gate: "Perform a full assessment and explain each abnormal finding by the physiology that produced it.",
      objectives: [
        "Health history taking and interviewing technique",
        "Inspection, palpation, percussion and auscultation",
        "Cardiovascular assessment and heart sounds",
        "Respiratory assessment and breath sounds",
        "Abdominal assessment and bowel sounds",
        "Neurological assessment, including level of consciousness",
        "Musculoskeletal and integumentary assessment",
        "Assessment across the lifespan and adjusting technique by age",
        "Cell injury, inflammation and repair",
        "Immunity, hypersensitivity and autoimmunity",
        "Fluid, electrolyte and acid-base regulation",
        "Acid-base interpretation from a blood gas",
        "Microbiology: organisms, transmission and antimicrobial action",
        "Laboratory value interpretation and trending",
        "Pharmacokinetics and pharmacodynamics",
        "Nutrition and its role in healing",
      ],
    },
    {
      title: "Medical-surgical nursing I",
      weight: 20,
      gate: "Manage an adult with a common condition and anticipate the complication that condition tends to produce.",
      objectives: [
        "Hypertension, heart failure and cardiomyopathy",
        "Coronary artery disease, angina and myocardial infarction",
        "Dysrhythmia recognition and nursing response",
        "Shock: recognising type, stage and urgency",
        "Peripheral arterial and venous disease",
        "COPD, asthma and respiratory failure",
        "Pneumonia, tuberculosis and pulmonary embolism",
        "Chest tubes, oxygen therapy and mechanical ventilation basics",
        "Acute and chronic kidney disease",
        "Dialysis: hemodialysis and peritoneal",
        "Fluid volume deficit and overload",
        "Diabetes mellitus and the acute crises DKA and HHS",
        "Thyroid, adrenal and pituitary disorders",
        "Perioperative nursing: before, during and after",
        "Wound healing, dehiscence and infection",
        "Pain management, including the opioid-tolerant patient",
        "Sepsis recognition and the first hour of response",
      ],
    },
    {
      title: "Medical-surgical nursing II and complex care",
      weight: 18,
      gate: "Care for a patient whose systems are failing together, and decide what to act on first.",
      objectives: [
        "Stroke: ischemic and hemorrhagic, and time-critical response",
        "Increased intracranial pressure",
        "Seizure disorders and status epilepticus",
        "Spinal cord injury and autonomic dysreflexia",
        "Neurodegenerative disease: Parkinson's, multiple sclerosis, ALS",
        "Dementia and delirium distinguished in practice",
        "Gastrointestinal bleeding and liver failure",
        "Pancreatitis and biliary disease",
        "Inflammatory bowel disease and ostomy management",
        "Cancer: treatment modalities and their toxicities",
        "Neutropenic precautions and oncologic emergencies",
        "Hematologic disorders: anemia, clotting and transfusion reaction",
        "Blood product administration and the reaction protocol",
        "Burns: depth, fluid resuscitation and infection risk",
        "Trauma and emergency triage",
        "Musculoskeletal trauma, traction and compartment syndrome",
        "Palliative and end-of-life care",
      ],
    },
    {
      title: "Maternal-newborn and pediatric nursing",
      weight: 16,
      gate: "Care for two patients at once during pregnancy and birth, and scale everything to the child in front of you.",
      objectives: [
        "Antepartum assessment and fetal surveillance",
        "Common complications of pregnancy: preeclampsia, gestational diabetes, placenta previa",
        "Labor stages and nursing care through each",
        "Fetal heart rate patterns and the response each demands",
        "Analgesia and anesthesia in labor",
        "Operative birth and cesarean care",
        "Postpartum assessment and hemorrhage management",
        "Postpartum mood disorders",
        "Newborn transition, assessment and Apgar scoring",
        "Newborn feeding, jaundice and thermoregulation",
        "High-risk newborn care",
        "Growth and development across childhood and adolescence",
        "Pediatric dosage, fluid and airway differences",
        "Congenital and acquired cardiac conditions in children",
        "Pediatric respiratory illness: bronchiolitis, croup, epiglottitis",
        "Childhood cancers and chronic illness support",
        "Immunisation schedules and parental questions about them",
        "Child abuse recognition and mandatory reporting",
      ],
    },
    {
      title: "Mental health, community and leadership",
      weight: 16,
      gate: "Move competently outside the hospital: the psychiatric unit, the community, and the charge nurse's decisions.",
      objectives: [
        "Therapeutic use of self and therapeutic communication",
        "Mental status examination",
        "Anxiety disorders and panic",
        "Mood disorders: depression and bipolar disorder",
        "Suicide risk assessment and safety planning",
        "Schizophrenia and psychotic disorders",
        "Personality disorders and consistent team response",
        "Eating disorders",
        "Substance use disorders, withdrawal and overdose",
        "Psychotropic medications and their serious adverse effects",
        "Crisis intervention and de-escalation",
        "Seclusion, restraint and the least restrictive principle",
        "Community and public health nursing roles",
        "Epidemiology, screening and herd immunity in practical terms",
        "Social determinants of health and how they present at the bedside",
        "Care coordination, discharge planning and transitions of care",
        "Leadership, conflict resolution and the charge nurse role",
        "Quality improvement and nurse-sensitive indicators",
        "Disaster preparedness and triage",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Bachelor of Science in Nursing.
//
// Structured on the ten Domains of the AACN Essentials. Note the edition:
// the Essentials were revised in 2026, and the revision matters here --
// the featured concept that was "Diversity, Equity, and Inclusion" in the
// 2021 edition is "Access, Connection, and Engagement" in the 2026 one.
// Anything written from memory would have the old list.
// ---------------------------------------------------------------------------
export const BSN_TRACK: SeedTrack = {
  code: "BSNRN",
  title: "BSN Nursing Coach",
  description:
    "Baccalaureate nursing organised the way the discipline organises itself: the ten Domains of the AACN Essentials, from knowledge for nursing practice through systems, informatics and professional formation.",
  trackType: "graduate",
  subcategorySlug: "nursing-degrees",
  freshnessModel: "academic_foundational",
  sourceUrl: "https://www.aacnnursing.org/essentials",
  sourceVerifiedAt: VERIFIED_AT,
  contentReviewDueAt: "2027-09-18T00:00:00Z",
  requiresAcknowledgement: true,
  disclaimerKey: NURSING_DISCLAIMER_KEY,
  disclaimerVersion: 1,
  credential: {
    ...AACN_PROVIDER,
    credentialSlug: "bachelor-of-science-in-nursing",
    credentialName: "Bachelor of Science in Nursing",
    credentialUrl: "https://www.aacnnursing.org/essentials",
    basis: "accreditation_standard",
    standardName: "The Essentials: Core Competencies for Professional Nursing Education",
    standardRevision: "2026 edition",
    status: "active",
    officialObjectivesUrl: "https://www.aacnnursing.org/essentials",
    lastVendorVerifiedAt: VERIFIED_AT,
    recommendedExperience:
      "Entry-level (Essentials Level 1) competencies for professional nursing education. Suits a prelicensure BSN student or an RN completing a BSN.",
    questionFormat: "Competency-based program assessment against the Essentials sub-competencies",
    passingScorePolicy: "Set by the program and its accreditor; licensure is by NCLEX-RN",
  },
  units: [
    {
      title: "Knowledge for Nursing Practice",
      weight: 11,
      gate: "Use disciplinary knowledge and knowledge from other fields together, and say which one you are leaning on.",
      objectives: [
        "Nursing as a discipline with its own body of knowledge",
        "Ways of knowing in nursing, and what each contributes",
        "Nursing theory and its use in framing practice",
        "Knowledge from the liberal arts applied to care",
        "Natural and social sciences underpinning nursing practice",
        "Translating evidence into a practice decision",
        "Clinical judgment as the product of knowledge plus reasoning",
        "Innovation in nursing practice and where it comes from",
        "Systems thinking applied to a clinical problem",
      ],
    },
    {
      title: "Person-Centered Care",
      weight: 14,
      gate: "Build care around the person and the people who matter to them, not around the diagnosis.",
      objectives: [
        "Person-centered care as holistic and individualised",
        "Establishing a caring relationship and presence",
        "Communicating effectively across difference",
        "Compassionate care: noticing vulnerability and responding to it",
        "Assessment as the foundation of individualised care",
        "Diagnosing, planning and evaluating with the person, not for them",
        "Coordinating care across settings and disciplines",
        "Family and important others as part of the unit of care",
        "Developmentally appropriate care across the lifespan",
        "Respecting dignity, preference and self-determination",
        "Cultural humility and responsiveness",
        "Managing pain and symptoms as a person experiences them",
        "Advocating for the person within the system",
      ],
    },
    {
      title: "Population Health",
      weight: 11,
      gate: "Move from one patient to a population, and name the partnership that would actually shift the outcome.",
      objectives: [
        "Population health across the prevention-to-management continuum",
        "Epidemiology and describing disease in a population",
        "Social determinants of health and their measurable effect",
        "Health equity and access, connection and engagement",
        "Community assessment and asset mapping",
        "Partnerships with public health, government, industry and community",
        "Health promotion and disease prevention at population scale",
        "Emergency preparedness and disaster response",
        "Environmental health and its clinical consequences",
        "Global health and cross-border health threats",
        "Health policy and how nurses influence it",
        "Advocacy for policy that improves population outcomes",
      ],
    },
    {
      title: "Scholarship for the Nursing Discipline",
      weight: 9,
      gate: "Read the evidence critically, and be able to say why a study should or should not change what you do.",
      objectives: [
        "The generation and synthesis of nursing knowledge",
        "Research process and design fundamentals",
        "Quantitative and qualitative approaches and what each answers",
        "Appraising evidence quality and level",
        "Statistical literacy sufficient to read a results table",
        "Translating research into practice change",
        "Evidence-based practice models",
        "Ethical conduct of research and human subject protection",
        "Disseminating findings to clinical and lay audiences",
      ],
    },
    {
      title: "Quality and Safety",
      weight: 11,
      gate: "Treat an error as a system signal: find the condition that allowed it, not the person who met it.",
      objectives: [
        "A culture of safety and psychological safety in teams",
        "Just culture, and distinguishing error from recklessness",
        "Human factors and error-producing conditions",
        "Root cause analysis and failure modes analysis",
        "Quality improvement methods and measurement",
        "Nurse-sensitive indicators and outcome data",
        "Standardisation, checklists and reducing variation",
        "Reporting near misses and adverse events",
        "Disclosure to patients and families after harm",
        "Minimising risk of harm to patients and to providers",
      ],
    },
    {
      title: "Interprofessional Partnerships",
      weight: 9,
      gate: "Work with other professions as colleagues with distinct expertise, and communicate across that difference under pressure.",
      objectives: [
        "Interprofessional communication and structured handoff",
        "Roles and scopes of other health professions",
        "Team dynamics and shared decision making",
        "Conflict engagement and resolution within teams",
        "Speaking up across a hierarchy when safety requires it",
        "Shared accountability for patient outcomes",
        "Partnering with patients and families as team members",
        "Interprofessional education and reflective team practice",
      ],
    },
    {
      title: "Systems-Based Practice",
      weight: 9,
      gate: "Explain how the system pays for, staffs and constrains the care you give, and where the leverage sits.",
      objectives: [
        "Healthcare delivery system structure and financing",
        "Payment models and their effect on care decisions",
        "Cost, value and stewardship of resources",
        "Care coordination across the continuum",
        "Transitions of care and the risks they carry",
        "Regulatory bodies, accreditation and their influence",
        "Organisational structure, culture and change",
        "Staffing, workload and their relationship to outcomes",
        "Risk management and legal exposure",
        "Advocating for system-level change",
      ],
    },
    {
      title: "Informatics and Healthcare Technologies",
      weight: 9,
      gate: "Use the record and the technology as clinical instruments, including knowing how they mislead.",
      objectives: [
        "Information and communication technology in nursing practice",
        "Electronic health records and structured documentation",
        "Clinical decision support and alert fatigue",
        "Data, information, knowledge and wisdom as a progression",
        "Standardised terminology in nursing documentation",
        "Data privacy, security and regulatory obligation",
        "Telehealth and remote monitoring",
        "Evaluating a digital health tool before trusting it",
        "Artificial intelligence in clinical tools, and its failure modes",
        "Using data to drive quality improvement",
      ],
    },
    {
      title: "Professionalism",
      weight: 9,
      gate: "Hold the standards of the profession when it is inconvenient, and know where they come from.",
      objectives: [
        "Professional identity formation in nursing",
        "The nursing code of ethics applied to real conflict",
        "Ethical decision-making frameworks",
        "Moral distress, moral courage and moral resilience",
        "Accountability for one's own practice and competence",
        "Professional comportment and civility",
        "Nursing's social contract with the public",
        "Regulation, licensure and professional standards",
        "Stewardship and advocacy as professional obligations",
      ],
    },
    {
      title: "Personal, Professional and Leadership Development",
      weight: 8,
      gate: "Build the practice you can sustain: self-awareness, lifelong learning, leadership, and the honesty to seek feedback.",
      objectives: [
        "Self-awareness and reflective practice",
        "Lifelong learning and continuing competence",
        "Seeking, receiving and acting on feedback",
        "Emotional intelligence in clinical relationships",
        "Resilience, wellbeing and burnout prevention",
        "Managing the personal cost of clinical work",
        "Leadership development at every level of practice",
        "Mentorship, precepting and being mentored",
        "Career planning and specialty progression",
        "Contributing to the advancement of the profession",
      ],
    },
  ],
};

export const NURSING_TRACKS: SeedTrack[] = [
  NCLEX_RN_TRACK,
  NCLEX_PN_TRACK,
  CNA_TRACK,
  LPN_TRACK,
  ADN_TRACK,
  BSN_TRACK,
];
